package pe.com.bbva.reniec.ui;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

import pe.com.bbva.reniec.dominio.Carga;
import pe.com.bbva.reniec.dominio.Detalle;
import pe.com.bbva.reniec.dominio.Valor;
import pe.com.bbva.reniec.exception.ValidacionException;
import pe.com.bbva.reniec.negocio.CargaMasivaService;
import pe.com.bbva.reniec.negocio.ConfiguracionService;
import pe.com.bbva.reniec.negocio.DetalleService;
import pe.com.bbva.reniec.utileria.AdjuntarReceiver;
import pe.com.bbva.reniec.utileria.Constante;
import pe.com.bbva.reniec.utileria.ExcelExport;
import pe.com.bbva.reniec.utileria.Inject;
import pe.com.bbva.reniec.utileria.ProcesarArchivo;
import pe.com.bbva.reniec.utileria.ProcesarCargaLDAP;
import pe.com.bbva.reniec.utileria.TableConstructor;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.terminal.StreamResource;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.ProgressIndicator;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.Upload.FinishedEvent;
import com.vaadin.ui.Upload.FinishedListener;
import com.vaadin.ui.Upload.StartedEvent;
import com.vaadin.ui.Upload.StartedListener;
import com.vaadin.ui.Upload.SucceededEvent;
import com.vaadin.ui.Upload.SucceededListener;
import com.vaadin.ui.VerticalLayout;

public class ConsultantesCargaMasivaUI extends CustomComponent implements
		ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout layoutTablaDetalles;
	@AutoGenerated
	private Table tableDetalle;
	@AutoGenerated
	private HorizontalLayout pnlFiltrosDetalles;
	@AutoGenerated
	private AbsoluteLayout layoutTablaCargas;
	@AutoGenerated
	private HorizontalLayout pnlFiltro;
	@AutoGenerated
	private Table tblListaCargas;
	@AutoGenerated
	private Button btnExportar;
	@AutoGenerated
	private Panel pnlCargaArch;
	@AutoGenerated
	private AbsoluteLayout pnlCargaContenido;
	@AutoGenerated
	private VerticalLayout pnlUploadFile;
	@AutoGenerated
	private ProgressIndicator proIndicador;
	@AutoGenerated
	private Button btnProcesar;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private PopupDateField datFecha;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private ComboBox cmbTipo;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private ComboBox cmbAplicacionOrigen;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private TextField txtId;
	@AutoGenerated
	private Label lblId;
	private static final long serialVersionUID = 1L;
	ArrayList<Object[]> cargaHeaders = new ArrayList<Object[]>();
	private BeanItemContainer<Valor> bicOrigen;
	private BeanItemContainer<Valor> bicTipo;
	private BeanItemContainer<Valor> bicEstado;
	private BeanItemContainer<Valor> bicEstadoReniec;
	AdjuntarReceiver fileReceiver = new AdjuntarReceiver();
	Upload uplArchivo = new Upload(null, fileReceiver);
	protected ByteArrayOutputStream outputStream;
	protected String nombreArchivo;
	protected String formatoDateArchivo = "yyyyMMdd";

	@Autowired
	CargaMasivaService cargaMasivaService;

	@Autowired
	ConfiguracionService configuracionService;

	@Autowired
	DetalleService detalleService;

	public ConsultantesCargaMasivaUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		Inject.inject(this);
		postConstruct();
	}

	private void postConstruct() {
		cargarDatosIniciales();
		cargaListeners();
		cargaReglasPanelCarga();
		cargaListenerUpload();

	}

	private void cargaListenerUpload() {
		pnlUploadFile.addComponent(uplArchivo, 0);
		uplArchivo.setImmediate(false);
		uplArchivo.setEnabled(false);
		uplArchivo.setButtonCaption(null);
		proIndicador.setVisible(false);

		uplArchivo.addListener(new StartedListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void uploadStarted(StartedEvent event) {
			}

		});
		uplArchivo.addListener(new SucceededListener() {

			private static final long serialVersionUID = 1L;

			public void uploadSucceeded(SucceededEvent event) {
				AdjuntarReceiver receiver = (AdjuntarReceiver) uplArchivo
						.getReceiver();
				outputStream = receiver.getOutputStream();
				nombreArchivo = receiver.getFileName();
			}
		});

		uplArchivo.addListener(new FinishedListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void uploadFinished(FinishedEvent event) {
				SimpleDateFormat formatoDate = new SimpleDateFormat(
						formatoDateArchivo);
				String nombreValidar = ((Valor) cmbAplicacionOrigen.getValue())
						.getCodigo()
						+ "."
						+ formatoDate.format(datFecha.getValue()) + ".txt";
				if (nombreValidar.equalsIgnoreCase(nombreArchivo)) {

					Valor estado = configuracionService.obtenerValorxCodigo(
							Constante.LISTA.CODIGO.REGISTRO_ESTADO,
							Constante.VALOR.REGISTRO_ESTADO.CODIGO.ACTIVO);
					ProcesarArchivo procesarArchivo = new ProcesarArchivo(
							outputStream);

					procesarArchivo.cargarArchivo((Valor) cmbTipo.getValue(),
							(Valor) cmbAplicacionOrigen.getValue(),
							(Date) datFecha.getValue(), nombreArchivo, estado,
							"");
					reconstruirTablaCargas();
					cargaReglasPanelCarga();

				} else {
					uplArchivo.interruptUpload();
					throw new ValidacionException(
							"Error Nombre del Archivo<br><br>",
							"validar.nombre.archivo",
							new Object[] { nombreArchivo });
				}

			}

		});
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	private void reconstruirTablaCargas() {
		TableConstructor tblConst = new TableConstructor();
		tblConst.setTblTablaLocal(tblListaCargas);
		tblConst.setModelo(Carga.class);
		tblConst.setContainer((IndexedContainer) tblListaCargas
				.getContainerDataSource());
		List<Carga> cargas = cargaMasivaService.obtenerCargasDesc();
		tblConst.construirTablaSimpleInterna(cargas);
		tableDetalle.setVisible(false);
		mainLayout.setHeight("290");
		setHeight("290");
		tblConst.limpiarFiltros(pnlFiltro);
	}

	private void cargaReglasPanelCarga() {
		txtId.setReadOnly(false);
		Long maxId = cargaMasivaService.obtenerUltimoId() + 1L;
		txtId.setValue(maxId);
		txtId.setReadOnly(true);
		Valor origen = configuracionService.obtenerValorxCodigo(
				Constante.LISTA.CODIGO.ORIGEN,
				Constante.VALOR.ORIGEN.CODIGO.LDAP);
		cmbAplicacionOrigen.setValue(origen);
		Valor tipoCarga = configuracionService.obtenerValorxCodigo(
				Constante.LISTA.CODIGO.CARGA_TIPO,
				Constante.VALOR.CARGA_TIPO.CODIGO.AUTOMATICA);
		cmbTipo.setValue(tipoCarga);
		datFecha.setDateFormat("dd-MM-yyyy");
		datFecha.setEnabled(false);
		datFecha.setValue(null);
		uplArchivo.setEnabled(false);

	}

	@SuppressWarnings("serial")
	private void cargaListeners() {
		btnProcesar.addListener(this);

		/* Especificaciones adicionales a la tabla principal de contenido */
		tblListaCargas.setSelectable(true);
		tblListaCargas.setImmediate(true);
		tblListaCargas.setNullSelectionAllowed(true);
		tblListaCargas.setNullSelectionItemId(null);
		tblListaCargas.addListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				Integer eleccion = (Integer) tblListaCargas.getValue();
				if (eleccion != null) {
					Item item = tblListaCargas.getItem(eleccion);
					tableDetalle.setVisible(true);
					crearTablaDetalle(item);
					mainLayout.setHeight("645");
					setHeight("620");
					
				} else {
					tableDetalle.setVisible(false);
					mainLayout.setHeight("290");
					setHeight("290");
				}

			}

		});

		btnExportar.addListener(this);
		tableDetalle.setImmediate(true);

		cmbAplicacionOrigen.addListener(new ValueChangeListener() {
			@Override
			public void valueChange(ValueChangeEvent event) {
				if (((Valor) cmbAplicacionOrigen.getValue()).getCodigo()
						.equals(Constante.VALOR.ORIGEN.CODIGO.LDAP)) {
					Valor tipoCarga = configuracionService.obtenerValorxCodigo(
							Constante.LISTA.CODIGO.CARGA_TIPO,
							Constante.VALOR.CARGA_TIPO.CODIGO.AUTOMATICA);
					cmbTipo.setValue(tipoCarga);
					cmbTipo.setReadOnly(true);
					datFecha.setEnabled(false);
					datFecha.setValue(null);
					uplArchivo.setEnabled(false);

				} else {
					cmbTipo.setReadOnly(false);
					datFecha.setEnabled(true);
					datFecha.setValue(new Date());
					uplArchivo.setEnabled(false);
				}
			}
		});

		Valor origen = configuracionService.obtenerValorxCodigo(
				Constante.LISTA.CODIGO.ORIGEN,
				Constante.VALOR.ORIGEN.CODIGO.LDAP);
		cmbAplicacionOrigen.setValue(origen);
		cmbTipo.addListener(new ValueChangeListener() {
			@Override
			public void valueChange(ValueChangeEvent event) {
				if (((Valor) cmbTipo.getValue()).getCodigo().equals(
						Constante.VALOR.CARGA_TIPO.CODIGO.AUTOMATICA)) {
					uplArchivo.setEnabled(false);
				} else {
					uplArchivo.setEnabled(true);
				}
			}
		});

	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	protected void crearTablaDetalle(Item item) {
		Detalle detalle = new Detalle();
		Carga carga = new Carga();
		Long idCarga = null;
		if (item != null) {			
			idCarga = (Long) item.getItemProperty("id").getValue();
			carga.setId(idCarga);
			detalle.setCarga(carga);			
		}
		List<Detalle> detalles = (item != null) ? detalleService.cargaDetallesPorCarga(idCarga)
				: new ArrayList<Detalle>();
		ArrayList<Object[]> orden = new ArrayList<Object[]>();
		orden.add(new Object[] { "id", 20, Long.class });
		orden.add(new Object[] { "nroFila", 80, Long.class });
		orden.add(new Object[] { "numeroDoi", 80, String.class });
		orden.add(new Object[] { "nombreCompleto", 148, String.class });
		orden.add(new Object[] { "accion", 130, String.class });
		orden.add(new Object[] { "estado", 100, Valor.class, bicEstadoReniec });
		orden.add(new Object[] { "mensaje", 130, String.class });
		TableConstructor tablaConstruct = new TableConstructor();
		tablaConstruct.construirTablaSimple(tableDetalle, Detalle.class,
				detalles, orden, pnlFiltrosDetalles, detalleService,
				"cargaDetallesCriteria");
		tablaConstruct.setNuevaInstancia(detalle);
	

	}

	private void cargarDatosIniciales() {
		List<Valor> listaOrigen = cargaMasivaService
				.obtenerValoresxLista(Constante.LISTA.CODIGO.ORIGEN);
		bicOrigen = new BeanItemContainer<Valor>(Valor.class, listaOrigen);
		cmbAplicacionOrigen.setContainerDataSource(bicOrigen);
		cmbAplicacionOrigen.setItemCaptionPropertyId("nombre");
		cmbAplicacionOrigen.setImmediate(true);
		cmbAplicacionOrigen.setNullSelectionAllowed(false);
		cmbAplicacionOrigen.setTextInputAllowed(false);

		List<Valor> listatipo = cargaMasivaService
				.obtenerValoresxLista(Constante.LISTA.CODIGO.CARGA_TIPO);
		bicTipo = new BeanItemContainer<Valor>(Valor.class, listatipo);
		cmbTipo.setContainerDataSource(bicTipo);
		cmbTipo.setItemCaptionPropertyId("nombre");
		cmbTipo.setImmediate(true);
		cmbTipo.setNullSelectionAllowed(false);
		cmbTipo.setTextInputAllowed(false);

		List<Valor> listaEstado = cargaMasivaService
				.obtenerValoresxLista(Constante.LISTA.CODIGO.REGISTRO_ESTADO);
		bicEstado = new BeanItemContainer<Valor>(Valor.class, listaEstado);
		
		List<Valor> listaEstadoReniec = cargaMasivaService
				.obtenerValoresxLista(Constante.LISTA.CODIGO.USUARIO_ESTADO);
		bicEstadoReniec = new BeanItemContainer<Valor>(Valor.class, listaEstadoReniec);
		crearTablaCargas();
		crearTablaDetalle(null);

	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void crearTablaCargas() {
		List<Carga> cargas = cargaMasivaService.obtenerCargasDesc();
		cargaHeaders.add(new Object[] { "id", 20, Long.class });
		cargaHeaders.add(new Object[] { "estado", 80, Valor.class, bicEstado });
		cargaHeaders.add(new Object[] { "tipo", 80, Valor.class, bicTipo });
		cargaHeaders
				.add(new Object[] { "origen", 130, Valor.class, bicOrigen });
		cargaHeaders.add(new Object[] { "inicio", 130, Date.class });
		cargaHeaders.add(new Object[] { "fin", 130, Date.class });
		cargaHeaders.add(new Object[] { "mensaje", 119, String.class });
		(new TableConstructor()).construirTablaSimple(tblListaCargas,
				Carga.class, cargas, cargaHeaders, pnlFiltro,
				cargaMasivaService, "obtenerCargasDescByCriteria");

	}

	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getButton() == btnExportar) {
			buttonClickExportarExcel();			
		}

		if (event.getButton() == btnProcesar) {
			if (((Valor) cmbAplicacionOrigen.getValue()).getCodigo().equals(
					Constante.VALOR.ORIGEN.CODIGO.LDAP)) {
				ProcesarCargaLDAP procesoLDAP = new ProcesarCargaLDAP();
				procesoLDAP.procesarCarga(new Date(), "");
				reconstruirTablaCargas();
			} else {
				if (datFecha.getValue() == null) {
					throw new ValidacionException("Error Fecha<br>",
							"validar.elegir", new Object[] { "Fecha" });
				} else {
					if (((Valor) cmbTipo.getValue()).getCodigo().equals(
							Constante.VALOR.CARGA_TIPO.CODIGO.MANUAL)) {
						fileReceiver = new AdjuntarReceiver();
						uplArchivo.setReceiver(fileReceiver);
						uplArchivo.submitUpload();

					} else {
						SimpleDateFormat formatoDate = new SimpleDateFormat(
								formatoDateArchivo);
						String nombreArchivo = ((Valor) cmbAplicacionOrigen
								.getValue()).getCodigo()
								+ "."
								+ formatoDate.format(datFecha.getValue())
								+ ".txt";
						Valor rutaArchivo = configuracionService
								.obtenerValorxCodigo(
										Constante.LISTA.CODIGO.RUTAS_ARCHIVOS,
										((Valor) cmbAplicacionOrigen.getValue())
												.getCodigo());

						String nombreRuta = rutaArchivo.getDescripcion()
								+ nombreArchivo;

						File archivo = new File(nombreRuta);
						if (!archivo.exists()) {
							throw new ValidacionException(
									"Error archivo<br><br>",
									"validar.existe.archivo",
									new Object[] { nombreArchivo });
						}

						try {
							InputStream inputStream = new FileInputStream(
									nombreRuta);

							Valor estado = configuracionService
									.obtenerValorxCodigo(
											Constante.LISTA.CODIGO.REGISTRO_ESTADO,
											Constante.VALOR.REGISTRO_ESTADO.CODIGO.ACTIVO);
							ProcesarArchivo procesarArchivo = new ProcesarArchivo(
									inputStream);

							procesarArchivo.cargarArchivo(
									(Valor) cmbTipo.getValue(),
									(Valor) cmbAplicacionOrigen.getValue(),
									(Date) datFecha.getValue(), nombreArchivo,
									estado, "");
							reconstruirTablaCargas();
							archivo.delete();
							cargaReglasPanelCarga();
						} catch (FileNotFoundException e) {
							throw new ValidacionException(
									"Error archivo<br><br>",
									"validar.error.archivo",
									new Object[] { nombreArchivo });
						}

					}
				}

			}

		}

	}

	private void buttonClickExportarExcel() {
		StreamResource resource = null;
		StreamResource.StreamSource source = new StreamResource.StreamSource() {
			private static final long serialVersionUID = 1L;

			public InputStream getStream() {
				ByteArrayOutputStream baos = null;
				Integer eleccion = (Integer) tblListaCargas.getValue();
				if (eleccion != null) {

					try {
						baos = ExcelExport.exportarCargaMasiva(tblListaCargas,
								tableDetalle);
					} catch (Exception e) {

						e.printStackTrace();
					}
				}
				return new ByteArrayInputStream(baos.toByteArray());
			}
		};

		resource = new StreamResource(source, "DetalleCargaMasiva.xls",
				getApplication());
		resource.setMIMEType("application/x-unknown");
		resource.setCacheTime(0);

		getApplication().getMainWindow().open(resource);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1182px");
		mainLayout.setHeight("290px");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("1182px");
		setHeight("290px");

		// pnlCargaArch
		pnlCargaArch = buildPnlCargaArch();
		mainLayout.addComponent(pnlCargaArch, "top:20.0px;left:821.0px;");

		// btnExportar
		btnExportar = new Button();
		btnExportar.setCaption("Exportar");
		btnExportar.setIcon(new ThemeResource("img/export_ico.png"));
		btnExportar.setImmediate(true);
		btnExportar.setWidth("119px");
		btnExportar.setHeight("-1px");
		mainLayout.addComponent(btnExportar, "top:294.0px;left:681.0px;");

		// layoutTablaCargas
		layoutTablaCargas = buildLayoutTablaCargas();
		mainLayout.addComponent(layoutTablaCargas, "top:10.0px;left:0.0px;");

		// layoutTablaDetalles
		layoutTablaDetalles = buildLayoutTablaDetalles();
		mainLayout.addComponent(layoutTablaDetalles, "top:322.0px;left:0.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPnlCargaArch() {
		// common part: create layout
		pnlCargaArch = new Panel();
		pnlCargaArch.setStyleName("panelDetalle");
		pnlCargaArch.setCaption("Carga");
		pnlCargaArch.setImmediate(false);
		pnlCargaArch.setWidth("320px");
		pnlCargaArch.setHeight("260px");

		// pnlCargaContenido
		pnlCargaContenido = buildPnlCargaContenido();
		pnlCargaArch.setContent(pnlCargaContenido);

		return pnlCargaArch;
	}

	@AutoGenerated
	private AbsoluteLayout buildPnlCargaContenido() {
		// common part: create layout
		pnlCargaContenido = new AbsoluteLayout();
		pnlCargaContenido.setImmediate(false);
		pnlCargaContenido.setWidth("100.0%");
		pnlCargaContenido.setHeight("239px");
		pnlCargaContenido.setMargin(false);

		// lblId
		lblId = new Label();
		lblId.setImmediate(false);
		lblId.setWidth("-1px");
		lblId.setHeight("20px");
		lblId.setValue("ID:");
		pnlCargaContenido.addComponent(lblId, "top:21.0px;left:7.0px;");

		// txtId
		txtId = new TextField();
		txtId.setImmediate(false);
		txtId.setWidth("143px");
		txtId.setHeight("-1px");
		pnlCargaContenido.addComponent(txtId, "top:17.0px;left:140.0px;");

		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("APLICACIÓN ORIGEN:");
		pnlCargaContenido.addComponent(label_1, "top:48.0px;left:7.0px;");

		// cmbAplicacionOrigen
		cmbAplicacionOrigen = new ComboBox();
		cmbAplicacionOrigen.setImmediate(false);
		cmbAplicacionOrigen.setWidth("-1px");
		cmbAplicacionOrigen.setHeight("-1px");
		pnlCargaContenido.addComponent(cmbAplicacionOrigen,
				"top:46.0px;left:140.0px;");

		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("TIPO:");
		pnlCargaContenido.addComponent(label_2, "top:75.0px;left:7.0px;");

		// cmbTipo
		cmbTipo = new ComboBox();
		cmbTipo.setImmediate(false);
		cmbTipo.setWidth("-1px");
		cmbTipo.setHeight("-1px");
		pnlCargaContenido.addComponent(cmbTipo, "top:73.0px;left:140.0px;");

		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("FECHA:");
		pnlCargaContenido.addComponent(label_3, "top:106.0px;left:7.0px;");

		// datFecha
		datFecha = new PopupDateField();
		datFecha.setImmediate(false);
		datFecha.setWidth("143px");
		datFecha.setHeight("-1px");
		pnlCargaContenido.addComponent(datFecha, "top:101.0px;left:140.0px;");

		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("ARCHIVO DE CARGA:");
		pnlCargaContenido.addComponent(label_4, "top:133.0px;left:7.0px;");

		// btnProcesar
		btnProcesar = new Button();
		btnProcesar.setCaption("PROCESAR");
		btnProcesar.setImmediate(true);
		btnProcesar.setWidth("-1px");
		btnProcesar.setHeight("-1px");
		pnlCargaContenido.addComponent(btnProcesar, "top:181.0px;left:12.0px;");

		// pnlUploadFile
		pnlUploadFile = buildPnlUploadFile();
		pnlCargaContenido.addComponent(pnlUploadFile,
				"top:127.0px;left:140.0px;");

		return pnlCargaContenido;
	}

	@AutoGenerated
	private VerticalLayout buildPnlUploadFile() {
		// common part: create layout
		pnlUploadFile = new VerticalLayout();
		pnlUploadFile.setImmediate(false);
		pnlUploadFile.setWidth("143px");
		pnlUploadFile.setHeight("-1px");
		pnlUploadFile.setMargin(false);

		// proIndicador
		proIndicador = new ProgressIndicator();
		proIndicador.setImmediate(false);
		proIndicador.setWidth("-1px");
		proIndicador.setHeight("-1px");
		pnlUploadFile.addComponent(proIndicador);

		return pnlUploadFile;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutTablaCargas() {
		// common part: create layout
		layoutTablaCargas = new AbsoluteLayout();
		layoutTablaCargas.setStyleName("div-overflowx");
		layoutTablaCargas.setImmediate(false);
		layoutTablaCargas.setWidth("800px");
		layoutTablaCargas.setHeight("275px");
		layoutTablaCargas.setMargin(false);

		// tblListaCargas
		tblListaCargas = new Table();
		tblListaCargas.setImmediate(false);
		tblListaCargas.setWidth("100.0%");
		tblListaCargas.setHeight("230px");
		layoutTablaCargas.addComponent(tblListaCargas,
				"top:27.0px;right:0.0px;left:0.0px;");

		// pnlFiltro
		pnlFiltro = new HorizontalLayout();
		pnlFiltro.setImmediate(false);
		pnlFiltro.setWidth("-1px");
		pnlFiltro.setHeight("-1px");
		pnlFiltro.setMargin(false);
		layoutTablaCargas.addComponent(pnlFiltro, "top:0.0px;left:0.0px;");

		return layoutTablaCargas;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutTablaDetalles() {
		// common part: create layout
		layoutTablaDetalles = new AbsoluteLayout();
		layoutTablaDetalles.setStyleName("div-overflowx");
		layoutTablaDetalles.setImmediate(false);
		layoutTablaDetalles.setWidth("800px");
		layoutTablaDetalles.setHeight("295px");
		layoutTablaDetalles.setMargin(false);

		// pnlFiltrosDetalles
		pnlFiltrosDetalles = new HorizontalLayout();
		pnlFiltrosDetalles.setImmediate(false);
		pnlFiltrosDetalles.setWidth("-1px");
		pnlFiltrosDetalles.setHeight("-1px");
		pnlFiltrosDetalles.setMargin(false);
		layoutTablaDetalles.addComponent(pnlFiltrosDetalles,
				"top:5.0px;left:0.0px;");

		// tableDetalle
		tableDetalle = new Table();
		tableDetalle.setImmediate(false);
		tableDetalle.setWidth("100.0%");
		tableDetalle.setHeight("245px");
		layoutTablaDetalles
				.addComponent(tableDetalle, "top:30.0px;left:0.0px;");

		return layoutTablaDetalles;
	}

}
