package pe.com.bbva.reniec.ui;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

import pe.com.bbva.reniec.dominio.Carga;
import pe.com.bbva.reniec.dominio.Valor;
import pe.com.bbva.reniec.negocio.CargaMasivaService;
import pe.com.bbva.reniec.utileria.Constante;
import pe.com.bbva.reniec.utileria.Inject;
import pe.com.bbva.reniec.utileria.TableConstructor;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;

public class ConsultantesCargaMasivaUI extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel pnlCargaArch;
	@AutoGenerated
	private AbsoluteLayout pnlCargaContenido;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Upload uplArchivo;
	@AutoGenerated
	private PopupDateField datFecha;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private ComboBox cmbTipo;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private ComboBox cmbAplicacionOrigen;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private TextField txtId;
	@AutoGenerated
	private Label lblId;
	@AutoGenerated
	private Table tblListaCargas;
	private static final long serialVersionUID = 1L;
	
	@Autowired
	CargaMasivaService cargaMasivaService;
	
	public ConsultantesCargaMasivaUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		Inject.inject(this);
		postConstruct();
	}

	private void postConstruct() {
		cargarDatosIniciales();	
	}

	private void cargarDatosIniciales() {
		crearTablaCargas();
		
		List<Valor> listaOrigen = cargaMasivaService.obtenerValoresxLista(Constante.LISTA.CODIGO.ORIGEN);
		BeanItemContainer<Valor> bicOrigen = new BeanItemContainer<Valor>(Valor.class,  listaOrigen);
		cmbAplicacionOrigen.setInputPrompt("Aplicación Origen");
		cmbAplicacionOrigen.setContainerDataSource(bicOrigen);
		cmbAplicacionOrigen.setItemCaptionPropertyId("nombre");
		cmbAplicacionOrigen.setImmediate(true);
		
		
	}




	private void crearTablaCargas() {
		List<Carga> cargas = cargaMasivaService.obtenerCargasDesc();
		ArrayList<Object> orden = new ArrayList<Object>();
		orden.add("id");
		orden.add("estado");
		orden.add("tipo");
		orden.add("origen");
		orden.add("inicio");
		orden.add("fin");
		orden.add("mensaje");		
		TableConstructor.construirTablaSimple(tblListaCargas, Carga.class, cargas, orden);	
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1182px");
		mainLayout.setHeight("800px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("1182px");
		setHeight("800px");
		
		// tblListaCargas
		tblListaCargas = new Table();
		tblListaCargas.setImmediate(false);
		tblListaCargas.setWidth("801px");
		tblListaCargas.setHeight("350px");
		mainLayout.addComponent(tblListaCargas, "top:20.0px;left:0.0px;");
		
		// pnlCargaArch
		pnlCargaArch = buildPnlCargaArch();
		mainLayout.addComponent(pnlCargaArch, "top:20.0px;left:821.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPnlCargaArch() {
		// common part: create layout
		pnlCargaArch = new Panel();
		pnlCargaArch.setStyleName("panelDetalle");
		pnlCargaArch.setCaption("Carga");
		pnlCargaArch.setImmediate(false);
		pnlCargaArch.setWidth("320px");
		pnlCargaArch.setHeight("350px");
		
		// pnlCargaContenido
		pnlCargaContenido = buildPnlCargaContenido();
		pnlCargaArch.setContent(pnlCargaContenido);
		
		return pnlCargaArch;
	}

	@AutoGenerated
	private AbsoluteLayout buildPnlCargaContenido() {
		// common part: create layout
		pnlCargaContenido = new AbsoluteLayout();
		pnlCargaContenido.setImmediate(false);
		pnlCargaContenido.setWidth("100.0%");
		pnlCargaContenido.setHeight("320px");
		pnlCargaContenido.setMargin(false);
		
		// lblId
		lblId = new Label();
		lblId.setImmediate(false);
		lblId.setWidth("-1px");
		lblId.setHeight("20px");
		lblId.setValue("ID:");
		pnlCargaContenido.addComponent(lblId, "top:21.0px;left:7.0px;");
		
		// txtId
		txtId = new TextField();
		txtId.setImmediate(false);
		txtId.setWidth("143px");
		txtId.setHeight("-1px");
		pnlCargaContenido.addComponent(txtId, "top:17.0px;left:140.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("APLICACIÓN ORIGEN:");
		pnlCargaContenido.addComponent(label_1, "top:48.0px;left:7.0px;");
		
		// cmbAplicacionOrigen
		cmbAplicacionOrigen = new ComboBox();
		cmbAplicacionOrigen.setImmediate(false);
		cmbAplicacionOrigen.setWidth("-1px");
		cmbAplicacionOrigen.setHeight("-1px");
		pnlCargaContenido.addComponent(cmbAplicacionOrigen,
				"top:46.0px;left:140.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("TIPO:");
		pnlCargaContenido.addComponent(label_2, "top:75.0px;left:7.0px;");
		
		// cmbTipo
		cmbTipo = new ComboBox();
		cmbTipo.setImmediate(false);
		cmbTipo.setWidth("-1px");
		cmbTipo.setHeight("-1px");
		cmbTipo.setInputPrompt("Tipo Carga");
		pnlCargaContenido.addComponent(cmbTipo, "top:73.0px;left:140.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("FECHA:");
		pnlCargaContenido.addComponent(label_3, "top:106.0px;left:7.0px;");
		
		// datFecha
		datFecha = new PopupDateField();
		datFecha.setImmediate(false);
		datFecha.setWidth("143px");
		datFecha.setHeight("-1px");
		pnlCargaContenido.addComponent(datFecha, "top:101.0px;left:140.0px;");
		
		// uplArchivo
		uplArchivo = new Upload();
		uplArchivo.setImmediate(false);
		uplArchivo.setWidth("160px");
		uplArchivo.setHeight("-1px");
		pnlCargaContenido.addComponent(uplArchivo, "top:130.0px;left:140.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("ARCHIVO DE CARGA:");
		pnlCargaContenido.addComponent(label_4, "top:133.0px;left:7.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("PROCESAR");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		pnlCargaContenido.addComponent(button_1, "top:181.0px;left:12.0px;");
		
		return pnlCargaContenido;
	}

}
