package pe.com.bbva.reniec.dominio.quartz;

// Generated 2/10/2013 03:54:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QrtzLocks generated by hbm2java
 */
@Entity
@Table(name = "QRTZ_LOCKS")
@SuppressWarnings("serial")
public class QrtzLocks implements java.io.Serializable {

	private String lockName;

	public QrtzLocks() {
	}

	public QrtzLocks(String lockName) {
		this.lockName = lockName;
	}

	@Id
	@Column(name = "LOCK_NAME", unique = true, nullable = false, length = 40)
	public String getLockName() {
		return this.lockName;
	}

	public void setLockName(String lockName) {
		this.lockName = lockName;
	}

}
