package pe.com.bbva.reniec.ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;

import pe.com.bbva.reniec.dominio.Consultante;
import pe.com.bbva.reniec.dominio.Valor;
import pe.com.bbva.reniec.negocio.ConsultantesService;
import pe.com.bbva.reniec.utileria.AlertDialog;
import pe.com.bbva.reniec.utileria.BeanValidar;
import pe.com.bbva.reniec.utileria.Constante;
import pe.com.bbva.reniec.utileria.Inject;
import pe.com.bbva.reniec.utileria.ReniecUtil;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.ShortcutListener;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.ui.AbstractTextField.TextChangeEventMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

@SuppressWarnings("serial")
public class ConsultantesUI extends CustomComponent implements TextChangeListener,ClickListener{

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout pnlLayout;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteLayout;
	@AutoGenerated
	private VerticalLayout pnlConsultanteContenido;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteBoton;
	@AutoGenerated
	private Button btnEstadoReniec;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteFila7;
	@AutoGenerated
	private HorizontalLayout pnlEstadoReniec;
	@AutoGenerated
	private ComboBox cmbEstadoReniec;
	@AutoGenerated
	private Label lblEstadoReniec;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteFila6;
	@AutoGenerated
	private ComboBox cmbEstado;
	@AutoGenerated
	private Label lblEstado;
	@AutoGenerated
	private TextField txtCentro;
	@AutoGenerated
	private Label lblCentro;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteFila5;
	@AutoGenerated
	private ComboBox cmbNacionalidad;
	@AutoGenerated
	private Label lblNacionalidad;
	@AutoGenerated
	private TextField txtCodigo;
	@AutoGenerated
	private Label lblCodigo;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteFila4;
	@AutoGenerated
	private PopupDateField pdfFecha;
	@AutoGenerated
	private Label lblFecha;
	@AutoGenerated
	private TextField txtNombres;
	@AutoGenerated
	private Label lblNombres;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteFila3;
	@AutoGenerated
	private TextField txtMaterno;
	@AutoGenerated
	private Label lblMaterno;
	@AutoGenerated
	private TextField txtPaterno;
	@AutoGenerated
	private Label lblPaterno;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteFila2;
	@AutoGenerated
	private TextField txtNumero;
	@AutoGenerated
	private Label lblNumero;
	@AutoGenerated
	private ComboBox cmbTipoDOI;
	@AutoGenerated
	private Label lblTipoDOI;
	@AutoGenerated
	private HorizontalLayout pnlConsultanteFila1;
	@AutoGenerated
	private ComboBox cmbAplicativo;
	@AutoGenerated
	private Label lblAplicativo;
	@AutoGenerated
	private TextField txtRegistro;
	@AutoGenerated
	private Label lblRegistro;
	@AutoGenerated
	private Label lblTituloConsultante;
	@AutoGenerated
	private VerticalLayout pnlTablaContenido;
	@AutoGenerated
	private Table tblConsultante;
	@AutoGenerated
	private HorizontalLayout pblTablaFiltro;
	@AutoGenerated
	private TextField txtAplicativoFiltro;
	@AutoGenerated
	private PopupDateField pdfFechaFiltro;
	@AutoGenerated
	private TextField txtEstadoFiltro;
	@AutoGenerated
	private TextField txtCentroFiltro;
	@AutoGenerated
	private TextField txtNacionalidadFiltro;
	@AutoGenerated
	private TextField txtCodigoFiltro;
	@AutoGenerated
	private TextField txtNombresFiltro;
	@AutoGenerated
	private TextField txtRegistroFiltro;
	
	@Autowired
	ConsultantesService consultantesService;

	DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
	Long id=null;
	
	public ConsultantesUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		Inject.inject(this);
		postConstruct();
	}

	public void postConstruct(){
		
		txtRegistroFiltro.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtRegistroFiltro.addListener((TextChangeListener)this);
		txtNombresFiltro.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtNombresFiltro.addListener((TextChangeListener)this);
		txtCodigoFiltro.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtCodigoFiltro.addListener((TextChangeListener)this);
		txtNacionalidadFiltro.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtNacionalidadFiltro.addListener((TextChangeListener)this);
		txtCentroFiltro.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtCentroFiltro.addListener((TextChangeListener)this);
		txtEstadoFiltro.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtEstadoFiltro.addListener((TextChangeListener)this);
		pdfFechaFiltro.setInputPrompt("Fecha");
		txtAplicativoFiltro.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtAplicativoFiltro.addListener((TextChangeListener)this);
		
		tblConsultante.setSelectable(true);
		tblConsultante.setImmediate(true);
		tblConsultante.setNullSelectionAllowed(true);
		tblConsultante.setNullSelectionItemId(null);
		tblConsultante.addListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				if(tblConsultante.getValue() == null){
					limpiar();
				}else{
					Item item = tblConsultante.getItem(tblConsultante.getValue());
					
					id=(Long)item.getItemProperty("id").getValue();
					txtRegistro.setValue(item.getItemProperty("registro").getValue());
					cmbTipoDOI.setValue(item.getItemProperty("tipoDOI").getValue());
					txtCodigo.setValue(item.getItemProperty("codigo").getValue());
					txtNumero.setValue(item.getItemProperty("numero").getValue());
					txtNombres.setValue(item.getItemProperty("nombres").getValue());
					txtPaterno.setValue(item.getItemProperty("paterno").getValue());
					txtMaterno.setValue(item.getItemProperty("materno").getValue());
					pdfFecha.setValue(item.getItemProperty("nacimiento").getValue());
					cmbNacionalidad.setValue(item.getItemProperty("nacionalidad").getValue());
					txtCentro.setValue(item.getItemProperty("centro").getValue());
					cmbAplicativo.setValue(item.getItemProperty("aplicativo").getValue());
					cmbEstado.setValue(item.getItemProperty("estado").getValue());
					cmbEstadoReniec.setValue(null);
					
				}
			}
		});
		
		cargarConsultante(null);
		
		txtRegistro.addShortcutListener(new ShortcutListener("", KeyCode.ENTER, null) {

			@Override
			public void handleAction(Object sender, Object target) {
					shortCutEnter(sender, target);
			}
		});
		
		txtRegistro.setNullRepresentation("");
		txtCodigo.setNullRepresentation("");
		txtNombres.setNullRepresentation("");
		txtPaterno.setNullRepresentation("");
		
		
		List<Valor> listTipoNacionalidad=consultantesService.obtenerValoresxLista(Constante.LISTA.CODIGO.NACIONALIDAD_TIPO);
		BeanItemContainer<Valor> bicTipoNacionalidad = new BeanItemContainer<Valor>(Valor.class,  listTipoNacionalidad);
		cmbNacionalidad.setInputPrompt("Nacionalidad");
		cmbNacionalidad.setContainerDataSource(bicTipoNacionalidad);
		cmbNacionalidad.setItemCaptionPropertyId("nombre");
		
		pdfFecha.setInputPrompt("FEC. NACIMIENTO");
		pdfFecha.setDateFormat("dd/MM/yyyy");
		
		List<Valor> listTipoDOI=consultantesService.obtenerValoresxLista(Constante.LISTA.CODIGO.DOI_TIPO);
		BeanItemContainer<Valor> bicTipoDOI = new BeanItemContainer<Valor>(Valor.class,  listTipoDOI);
		cmbTipoDOI.setInputPrompt("Tipo DOI");
		cmbTipoDOI.setContainerDataSource(bicTipoDOI);
		cmbTipoDOI.setItemCaptionPropertyId("nombre");
		cmbTipoDOI.setImmediate(true);
		cmbTipoDOI.addListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				Valor tipoDOI=(Valor)cmbTipoDOI.getValue();
				txtCodigo.setEnabled(true);
				txtNumero.setMaxLength(-1);
				if(tipoDOI!=null){
					int longitud=Constante.VALOR.DOI_TIPO.LONGITUD.valueOf(tipoDOI.getCodigo()).getValor();
					String numero=(String)txtNumero.getValue();
					txtNumero.setValue(StringUtils.substring(numero, 0, longitud));
					txtNumero.setMaxLength(longitud);
					if(tipoDOI.getCodigo().equals(Constante.VALOR.DOI_TIPO.CODIGO.DNI)){
						txtCodigo.setEnabled(false);
						txtCodigo.setValue(txtNumero.getValue());
					}
				}
			}
		});
		
		txtNumero.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtNumero.addListener((TextChangeListener)this);
		txtNumero.setNullRepresentation("");
		
		txtMaterno.setNullRepresentation("");
		txtCentro.setNullRepresentation("");
		
		List<Valor> listOrigen=consultantesService.obtenerValoresxLista(Constante.LISTA.CODIGO.ORIGEN);
		BeanItemContainer<Valor> bicOrigen = new BeanItemContainer<Valor>(Valor.class,  listOrigen);
		cmbAplicativo.setInputPrompt("Aplicativo Origen");
		cmbAplicativo.setContainerDataSource(bicOrigen);
		cmbAplicativo.setItemCaptionPropertyId("nombre");
		cmbAplicativo.setImmediate(true);
		cmbAplicativo.addListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				obtenerLdap();
			}
		});
		
		List<Valor> listEstadoUsuario=consultantesService.obtenerValoresxLista(Constante.LISTA.CODIGO.USUARIO_ESTADO);
		BeanItemContainer<Valor> bicEstadoUsuario = new BeanItemContainer<Valor>(Valor.class,  listEstadoUsuario);
		cmbEstado.setInputPrompt("Estado");
		cmbEstado.setContainerDataSource(bicEstadoUsuario);
		cmbEstado.setItemCaptionPropertyId("nombre");
		
		List<Valor> listSituacionReniec=consultantesService.obtenerValoresxLista(Constante.LISTA.CODIGO.RENIEC_SITUACION);
		BeanItemContainer<Valor> bicSituacionReniec = new BeanItemContainer<Valor>(Valor.class,  listSituacionReniec);
		cmbEstadoReniec.setInputPrompt("Estado Reniec");
		cmbEstadoReniec.setContainerDataSource(bicSituacionReniec);
		cmbEstadoReniec.setItemCaptionPropertyId("nombre");
		cmbEstadoReniec.setEnabled(false);
		
		btnGuardar.addListener(this);
		btnEstadoReniec.addListener(this);
		
	}
	
	private void shortCutEnter(Object sender, Object target){
		if(txtRegistro.equals(target)){
			obtenerLdap();
		}
	}
	
	private void obtenerLdap(){
		Valor origen=(Valor)cmbAplicativo.getValue();
		if(origen!=null && origen.getCodigo().equals(Constante.VALOR.ORIGEN.CODIGO.LDAP)){
			String registro=(String)txtRegistro.getValue();
			registro=registro.toUpperCase();
			Consultante consultante=consultantesService.obtenerConsultanteLDAP(registro, origen);
			if(consultante!=null){
				id=consultante.getId();
				txtRegistro.setValue(consultante.getIdentificador());
				cmbTipoDOI.setValue(consultante.getTipoDOI());
				txtCodigo.setValue(consultante.getCodigoReniec());
				txtNumero.setValue(consultante.getDoi());
				txtNombres.setValue(consultante.getNombres());
				txtPaterno.setValue(consultante.getPaterno());
				txtMaterno.setValue(consultante.getMaterno());
				pdfFecha.setValue(consultante.getNacimiento());
				cmbNacionalidad.setValue(consultante.getNacionalidad());
				txtCentro.setValue(consultante.getCentro());
				cmbAplicativo.setValue(consultante.getOrigen());
				cmbEstado.setValue(consultante.getEstado());
				cmbEstadoReniec.setValue(null);
			}
		}
	}
	
	private void cargarConsultante(Consultante filtro){
		List<Consultante> listConsultante=consultantesService.obtenerConsultante(filtro);
		
		IndexedContainer container = new IndexedContainer();
		
		container.addContainerProperty("id", Long.class,  null);
		container.addContainerProperty("registro", String.class,  null);
		container.addContainerProperty("nombreCompleto", String.class,  null);
		container.addContainerProperty("nombres", String.class,  null);
		container.addContainerProperty("paterno", String.class,  null);
		container.addContainerProperty("materno", String.class,  null);
		container.addContainerProperty("codigo", String.class,  null);
		container.addContainerProperty("tipoDOI", Valor.class,  null);
		container.addContainerProperty("nacionalidadNombre", String.class,  null);
		container.addContainerProperty("nacionalidad", Valor.class,  null);
		container.addContainerProperty("centro", String.class,  null);
		container.addContainerProperty("estadoNombre", String.class,  null);
		container.addContainerProperty("estado", Valor.class,  null);
		container.addContainerProperty("estadoReniec", Valor.class,  null);
		container.addContainerProperty("fecha", Date.class,  null);
		container.addContainerProperty("nacimiento", Date.class,  null);
		container.addContainerProperty("aplicativoNombre", String.class,  null);
		container.addContainerProperty("aplicativo", Valor.class,  null);
		container.addContainerProperty("numero", String.class,  null);
		
		int con=1;
		for (Consultante consultante : listConsultante) {
			Item item = container.addItem(con++);
            item.getItemProperty("id").setValue(consultante.getId());
            item.getItemProperty("registro").setValue(consultante.getIdentificador());
            item.getItemProperty("nombreCompleto").setValue(consultante.getNombreCompleto());
            item.getItemProperty("nombres").setValue(consultante.getNombres());
            item.getItemProperty("paterno").setValue(consultante.getPaterno());
            item.getItemProperty("materno").setValue(consultante.getMaterno());
            item.getItemProperty("codigo").setValue(consultante.getCodigoReniec());
            item.getItemProperty("tipoDOI").setValue(consultante.getTipoDOI());
            item.getItemProperty("nacionalidadNombre").setValue(consultante.getNacionalidad()==null ?
            		null : consultante.getNacionalidad().getNombre());
            item.getItemProperty("nacionalidad").setValue(consultante.getNacionalidad());
            item.getItemProperty("centro").setValue(consultante.getCentro());
            item.getItemProperty("estadoNombre").setValue(consultante.getEstado() == null ? 
            		null : consultante.getEstado().getNombre());
            item.getItemProperty("estado").setValue(consultante.getEstado());
            item.getItemProperty("estadoReniec").setValue(consultante.getSituacion());
            item.getItemProperty("fecha").setValue(consultante.getEdicion()==null? consultante.getCreacion():consultante.getEdicion());
            item.getItemProperty("nacimiento").setValue(consultante.getNacimiento());
            item.getItemProperty("aplicativoNombre").setValue(consultante.getOrigen() == null ? 
            		null : consultante.getOrigen().getNombre());
            item.getItemProperty("aplicativo").setValue(consultante.getOrigen());
            item.getItemProperty("numero").setValue(consultante.getDoi());
		}
		
		tblConsultante.setContainerDataSource(container);
		tblConsultante.setVisibleColumns(new Object[]{"registro", "nombreCompleto", "codigo", "nacionalidadNombre",
				"centro","estadoNombre","fecha","aplicativoNombre"});
		tblConsultante.setColumnWidth("registro", 50);
		tblConsultante.setColumnWidth("nombreCompleto", 130);
		tblConsultante.setColumnWidth("codigo", 60);
		tblConsultante.setColumnWidth("nacionalidadNombre", 70);
		tblConsultante.setColumnWidth("centro", 45);
		tblConsultante.setColumnWidth("estadoNombre", 50);
		tblConsultante.setColumnWidth("fecha", 65);
		tblConsultante.setColumnWidth("aplicativoNombre", 65);
		tblConsultante.setColumnHeader("registro", "Registro");
		tblConsultante.setColumnHeader("nombreCompleto", "Nombres");
		tblConsultante.setColumnHeader("codigo", "Codigo");
		tblConsultante.setColumnHeader("nacionalidadNombre", "Nacionalidad");
		tblConsultante.setColumnHeader("centro", "Centro");
		tblConsultante.setColumnHeader("estadoNombre", "Estado");
		tblConsultante.setColumnHeader("fecha", "Fecha");
		tblConsultante.setColumnHeader("aplicativoNombre", "Aplicativo");
	}
	
	private void limpiar(){
		id=null;
		txtRegistro.setValue(StringUtils.EMPTY);
		txtCodigo.setValue(StringUtils.EMPTY);
		cmbTipoDOI.setValue(null);
		txtNumero.setValue(StringUtils.EMPTY);
		txtNombres.setValue(StringUtils.EMPTY);
		txtPaterno.setValue(StringUtils.EMPTY);
		txtMaterno.setValue(StringUtils.EMPTY);
		pdfFecha.setValue(null);
		cmbNacionalidad.setValue(null);
		txtCentro.setValue(StringUtils.EMPTY);
		cmbAplicativo.setValue(null);
		cmbEstado.setValue(null);
		cmbEstadoReniec.setValue(null);
		tblConsultante.setValue(null);
	}
	
	@Override
	public void buttonClick(ClickEvent event) {
		if(event.getButton().equals(btnGuardar)){
			Consultante consultante=new Consultante();
			consultante.setId(id);
			consultante.setIdentificador((String)txtRegistro.getValue());
			consultante.setCodigoReniec((String)txtCodigo.getValue());
			consultante.setTipoDOI((Valor)cmbTipoDOI.getValue());
			consultante.setDoi((String)txtNumero.getValue());
			consultante.setNombres((String)txtNombres.getValue());
			consultante.setPaterno((String)txtPaterno.getValue());
			consultante.setMaterno((String)txtMaterno.getValue());
			consultante.setNacimiento((Date)pdfFecha.getValue());
			consultante.setNacionalidad((Valor)cmbNacionalidad.getValue());
			consultante.setCentro((String)txtCentro.getValue());
			consultante.setOrigen((Valor)cmbAplicativo.getValue());
			consultante.setEstado((Valor)cmbEstado.getValue());
			ReniecUtil.validar(getWindow(), consultante, 
			new BeanValidar[]{new BeanValidar("identificador", new Object[]{"REGISTRO/USUARIO"}, txtRegistro),
				new BeanValidar("origen", new Object[]{"APLICATIVO ORIGEN"}, cmbAplicativo),
				new BeanValidar("tipoDOI", new Object[]{"TIPO DOI"}, cmbTipoDOI),
				new BeanValidar("doi", new Object[]{"NUMERO DOI"}, txtNumero),
				new BeanValidar("paterno", new Object[]{"AP. PATERNO"}, txtPaterno),
				new BeanValidar("nombres", new Object[]{"NOMBRES"}, txtNombres),
				new BeanValidar("nacimiento", new Object[]{"FEC. NACIMIENTO"}, pdfFecha),
				new BeanValidar("codigoReniec", new Object[]{"CÓDIGO/DNI"}, txtCodigo),
				new BeanValidar("nacionalidad", new Object[]{"NACIONALIDAD"}, cmbNacionalidad),
				new BeanValidar("centro", new Object[]{"CENTRO DE COSTO"}, txtCentro),
				new BeanValidar("estado", new Object[]{"ESTADO"}, cmbEstado)});
			String resultado=consultantesService.guardarConsultanteUI(consultante);
			if(!consultante.getNacionalidad().getCodigo().equals(Constante.VALOR.NACIONALIDAD_TIPO.CODIGO.EXTRANJERO)){
				if(resultado.equals(Constante.WS_RENIEC.SALIDA.ERROR.NINGUN_ERROR)){
					AlertDialog window=new AlertDialog("","Los datos han sido guardados con éxito","Aceptar","500px");
					
					Window windowHarec=getApplication().getMainWindow().getWindow();
					windowHarec.getWindow().addWindow(window);
				}else{
					String mensaje=Constante.WS_RENIEC.SALIDA.CODIGO_ERROR.get(resultado);
					mensaje=StringUtils.isBlank(mensaje)?resultado:mensaje;
					AlertDialog window=new AlertDialog("","Los datos han sido guardados, pero hubo una incidencia en RENIEC, por favor reintentar. Error "+resultado,"Aceptar","500px");
					
					Window windowHarec=getApplication().getMainWindow().getWindow();
					windowHarec.getWindow().addWindow(window);
				}
			}else{
				AlertDialog window=new AlertDialog("","Los datos han sido guardados con éxito","Aceptar","500px");
				
				Window windowHarec=getApplication().getMainWindow().getWindow();
				windowHarec.getWindow().addWindow(window);
			}
			limpiar();
			txtRegistroFiltro.setValue(StringUtils.EMPTY);
			txtNombresFiltro.setValue(StringUtils.EMPTY);
			txtCodigoFiltro.setValue(StringUtils.EMPTY);
			txtNacionalidadFiltro.setValue(StringUtils.EMPTY);
			txtCentroFiltro.setValue(StringUtils.EMPTY);
			txtEstadoFiltro.setValue(StringUtils.EMPTY);
			pdfFechaFiltro.setValue(null);
			txtAplicativoFiltro.setValue(StringUtils.EMPTY);
			cargarConsultante(null);
		}
		if(event.getButton().equals(btnEstadoReniec)){
			Consultante consultante=new Consultante();
			consultante.setId(id);
			consultante.setIdentificador((String)txtRegistro.getValue());
			consultante.setCodigoReniec((String)txtCodigo.getValue());
			consultante.setTipoDOI((Valor)cmbTipoDOI.getValue());
			consultante.setDoi((String)txtNumero.getValue());
			consultante.setNombres((String)txtNombres.getValue());
			consultante.setPaterno((String)txtPaterno.getValue());
			consultante.setMaterno((String)txtMaterno.getValue());
			consultante.setNacimiento((Date)pdfFecha.getValue());
			consultante.setNacionalidad((Valor)cmbNacionalidad.getValue());
			consultante.setCentro((String)txtCentro.getValue());
			consultante.setOrigen((Valor)cmbAplicativo.getValue());
			consultante.setEstado((Valor)cmbEstado.getValue());
			Valor estadoReniec=consultantesService.obtenerEstadoReniec(consultante);
			cmbEstadoReniec.setValue(estadoReniec);
		}
	}

	@Override
	public void textChange(TextChangeEvent event) {
		if(event.getSource().equals(txtNumero)){
			Valor tipoDOI=(Valor)cmbTipoDOI.getValue();
			if(tipoDOI!=null && tipoDOI.getCodigo().equals(Constante.VALOR.DOI_TIPO.CODIGO.DNI)){
				txtCodigo.setValue(event.getText());
			}
			return;
		}
		Consultante consultante=obtenerFiltros();
		if(event.getSource().equals(txtRegistroFiltro))
		{
			if(StringUtils.isNotBlank(event.getText()))
			{
				consultante.setIdentificador(event.getText());
			}
		}
		if(event.getSource().equals(txtNombresFiltro))
		{
			if(StringUtils.isNotBlank(event.getText()))
			{
				consultante.setNombres(event.getText());
			}
		}
		if(event.getSource().equals(txtCodigoFiltro))
		{
			if(StringUtils.isNotBlank(event.getText()))
			{
				consultante.setCodigoReniec(event.getText());
			}
		}
		if(event.getSource().equals(txtNacionalidadFiltro))
		{
			if(StringUtils.isNotBlank(event.getText()))
			{
				Valor nacionalidad = new Valor();
				nacionalidad.setNombre(event.getText());
				consultante.setNacionalidad(nacionalidad);
			}
		}
		if(event.getSource().equals(txtCentroFiltro))
		{
			if(StringUtils.isNotBlank(event.getText()))
			{
				consultante.setCentro(event.getText());
			}
		}
		if(event.getSource().equals(txtEstadoFiltro))
		{
			if(StringUtils.isNotBlank(event.getText()))
			{
				Valor estado = new Valor();
				estado.setNombre(event.getText());
				consultante.setEstado(estado);
			}
		}
		if(event.getSource().equals(txtAplicativoFiltro))
		{
			if(StringUtils.isNotBlank(event.getText()))
			{
				Valor aplicativo = new Valor();
				aplicativo.setNombre(event.getText());
				consultante.setOrigen(aplicativo);
			}
		}
		cargarConsultante(consultante);
	}
	
	private Consultante obtenerFiltros(){
		Consultante consultante=new Consultante();
		if(StringUtils.isNotBlank(txtRegistroFiltro.getValue().toString()))
		{
			consultante.setIdentificador(txtRegistroFiltro.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtNombresFiltro.getValue().toString()))
		{
			consultante.setNombres(txtNombresFiltro.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtCodigoFiltro.getValue().toString()))
		{
			consultante.setCodigoReniec(txtCodigoFiltro.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtNacionalidadFiltro.getValue().toString()))
		{
			Valor nacionalidad = new Valor();
			nacionalidad.setNombre(txtNacionalidadFiltro.getValue().toString());
			consultante.setNacionalidad(nacionalidad);
		}
		if(StringUtils.isNotBlank(txtCentroFiltro.getValue().toString()))
		{
			consultante.setCentro(txtCentroFiltro.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtEstadoFiltro.getValue().toString()))
		{
			Valor estado = new Valor();
			estado.setNombre(txtEstadoFiltro.getValue().toString());
			consultante.setEstado(estado);
		}
		if(StringUtils.isNotBlank(txtAplicativoFiltro.getValue().toString()))
		{
			Valor aplicativo = new Valor();
			aplicativo.setNombre(txtAplicativoFiltro.getValue().toString());
			consultante.setOrigen(aplicativo);
		}
		return consultante;
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// pnlLayout
		pnlLayout = buildPnlLayout();
		mainLayout.addComponent(pnlLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlLayout() {
		// common part: create layout
		pnlLayout = new VerticalLayout();
		pnlLayout.setImmediate(false);
		pnlLayout.setWidth("-1px");
		pnlLayout.setHeight("-1px");
		pnlLayout.setMargin(false);
		
		// pnlConsultanteLayout
		pnlConsultanteLayout = buildPnlConsultanteLayout();
		pnlLayout.addComponent(pnlConsultanteLayout);
		
		return pnlLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteLayout() {
		// common part: create layout
		pnlConsultanteLayout = new HorizontalLayout();
		pnlConsultanteLayout.setImmediate(false);
		pnlConsultanteLayout.setWidth("-1px");
		pnlConsultanteLayout.setHeight("-1px");
		pnlConsultanteLayout.setMargin(false);
		pnlConsultanteLayout.setSpacing(true);
		
		// pnlTablaContenido
		pnlTablaContenido = buildPnlTablaContenido();
		pnlConsultanteLayout.addComponent(pnlTablaContenido);
		
		// pnlConsultanteContenido
		pnlConsultanteContenido = buildPnlConsultanteContenido();
		pnlConsultanteLayout.addComponent(pnlConsultanteContenido);
		
		return pnlConsultanteLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlTablaContenido() {
		// common part: create layout
		pnlTablaContenido = new VerticalLayout();
		pnlTablaContenido.setImmediate(false);
		pnlTablaContenido.setWidth("-1px");
		pnlTablaContenido.setHeight("-1px");
		pnlTablaContenido.setMargin(false);
		
		// pblTablaFiltro
		pblTablaFiltro = buildPblTablaFiltro();
		pnlTablaContenido.addComponent(pblTablaFiltro);
		
		// tblConsultante
		tblConsultante = new Table(){

			@Override
			protected String formatPropertyValue(Object rowId, Object colId,
					Property property) {
				if (property.getType() == Date.class && property.getValue()!=null) {
					return fmt.format((Date)property.getValue());
		        }
				return super.formatPropertyValue(rowId, colId, property);
			}
			
		};
		tblConsultante.setImmediate(false);
		tblConsultante.setWidth("650px");
		tblConsultante.setHeight("300px");
		pnlTablaContenido.addComponent(tblConsultante);
		
		return pnlTablaContenido;
	}

	@AutoGenerated
	private HorizontalLayout buildPblTablaFiltro() {
		// common part: create layout
		pblTablaFiltro = new HorizontalLayout();
		pblTablaFiltro.setImmediate(false);
		pblTablaFiltro.setWidth("-1px");
		pblTablaFiltro.setHeight("-1px");
		pblTablaFiltro.setMargin(false);
		
		// txtRegistroFiltro
		txtRegistroFiltro = new TextField();
		txtRegistroFiltro.setImmediate(false);
		txtRegistroFiltro.setWidth("63px");
		txtRegistroFiltro.setHeight("-1px");
		txtRegistroFiltro.setInputPrompt("Registro");
		pblTablaFiltro.addComponent(txtRegistroFiltro);
		
		// txtNombresFiltro
		txtNombresFiltro = new TextField();
		txtNombresFiltro.setImmediate(false);
		txtNombresFiltro.setWidth("143px");
		txtNombresFiltro.setHeight("-1px");
		txtNombresFiltro.setInputPrompt("Nombres");
		pblTablaFiltro.addComponent(txtNombresFiltro);
		
		// txtCodigoFiltro
		txtCodigoFiltro = new TextField();
		txtCodigoFiltro.setImmediate(false);
		txtCodigoFiltro.setWidth("73px");
		txtCodigoFiltro.setHeight("-1px");
		txtCodigoFiltro.setInputPrompt("Codigo");
		pblTablaFiltro.addComponent(txtCodigoFiltro);
		
		// txtNacionalidadFiltro
		txtNacionalidadFiltro = new TextField();
		txtNacionalidadFiltro.setImmediate(false);
		txtNacionalidadFiltro.setWidth("83px");
		txtNacionalidadFiltro.setHeight("-1px");
		txtNacionalidadFiltro.setInputPrompt("Nacionalidad");
		pblTablaFiltro.addComponent(txtNacionalidadFiltro);
		
		// txtCentroFiltro
		txtCentroFiltro = new TextField();
		txtCentroFiltro.setImmediate(false);
		txtCentroFiltro.setWidth("58px");
		txtCentroFiltro.setHeight("-1px");
		txtCentroFiltro.setInputPrompt("Centro");
		pblTablaFiltro.addComponent(txtCentroFiltro);
		
		// txtEstadoFiltro
		txtEstadoFiltro = new TextField();
		txtEstadoFiltro.setImmediate(false);
		txtEstadoFiltro.setWidth("63px");
		txtEstadoFiltro.setHeight("-1px");
		txtEstadoFiltro.setInputPrompt("Estado");
		pblTablaFiltro.addComponent(txtEstadoFiltro);
		
		// pdfFechaFiltro
		pdfFechaFiltro = new PopupDateField();
		pdfFechaFiltro.setImmediate(false);
		pdfFechaFiltro.setWidth("78px");
		pdfFechaFiltro.setHeight("-1px");
		pdfFechaFiltro.setInvalidAllowed(false);
		pblTablaFiltro.addComponent(pdfFechaFiltro);
		
		// txtAplicativoFiltro
		txtAplicativoFiltro = new TextField();
		txtAplicativoFiltro.setImmediate(false);
		txtAplicativoFiltro.setWidth("78px");
		txtAplicativoFiltro.setHeight("-1px");
		txtAplicativoFiltro.setInputPrompt("Aplicativo");
		pblTablaFiltro.addComponent(txtAplicativoFiltro);
		
		return pblTablaFiltro;
	}

	@AutoGenerated
	private VerticalLayout buildPnlConsultanteContenido() {
		// common part: create layout
		pnlConsultanteContenido = new VerticalLayout();
		pnlConsultanteContenido.setImmediate(false);
		pnlConsultanteContenido.setWidth("-1px");
		pnlConsultanteContenido.setHeight("-1px");
		pnlConsultanteContenido.setMargin(false);
		pnlConsultanteContenido.setSpacing(true);
		
		// lblTituloConsultante
		lblTituloConsultante = new Label();
		lblTituloConsultante.setImmediate(false);
		lblTituloConsultante.setWidth("-1px");
		lblTituloConsultante.setHeight("-1px");
		lblTituloConsultante.setValue("USUARIO RENIEC");
		pnlConsultanteContenido.addComponent(lblTituloConsultante);
		pnlConsultanteContenido.setComponentAlignment(lblTituloConsultante,
				new Alignment(20));
		
		// pnlConsultanteFila1
		pnlConsultanteFila1 = buildPnlConsultanteFila1();
		pnlConsultanteContenido.addComponent(pnlConsultanteFila1);
		
		// pnlConsultanteFila2
		pnlConsultanteFila2 = buildPnlConsultanteFila2();
		pnlConsultanteContenido.addComponent(pnlConsultanteFila2);
		
		// pnlConsultanteFila3
		pnlConsultanteFila3 = buildPnlConsultanteFila3();
		pnlConsultanteContenido.addComponent(pnlConsultanteFila3);
		
		// pnlConsultanteFila4
		pnlConsultanteFila4 = buildPnlConsultanteFila4();
		pnlConsultanteContenido.addComponent(pnlConsultanteFila4);
		
		// pnlConsultanteFila5
		pnlConsultanteFila5 = buildPnlConsultanteFila5();
		pnlConsultanteContenido.addComponent(pnlConsultanteFila5);
		
		// pnlConsultanteFila6
		pnlConsultanteFila6 = buildPnlConsultanteFila6();
		pnlConsultanteContenido.addComponent(pnlConsultanteFila6);
		
		// pnlConsultanteFila7
		pnlConsultanteFila7 = buildPnlConsultanteFila7();
		pnlConsultanteContenido.addComponent(pnlConsultanteFila7);
		
		// pnlConsultanteBoton
		pnlConsultanteBoton = buildPnlConsultanteBoton();
		pnlConsultanteContenido.addComponent(pnlConsultanteBoton);
		
		return pnlConsultanteContenido;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteFila1() {
		// common part: create layout
		pnlConsultanteFila1 = new HorizontalLayout();
		pnlConsultanteFila1.setImmediate(false);
		pnlConsultanteFila1.setWidth("-1px");
		pnlConsultanteFila1.setHeight("-1px");
		pnlConsultanteFila1.setMargin(false);
		pnlConsultanteFila1.setSpacing(true);
		
		// lblRegistro
		lblRegistro = new Label();
		lblRegistro.setImmediate(false);
		lblRegistro.setWidth("130px");
		lblRegistro.setHeight("-1px");
		lblRegistro.setValue("REGISTRO/USUARIO:");
		pnlConsultanteFila1.addComponent(lblRegistro);
		
		// txtRegistro
		txtRegistro = new TextField();
		txtRegistro.setImmediate(false);
		txtRegistro.setWidth("100px");
		txtRegistro.setHeight("-1px");
		txtRegistro.setInputPrompt("REGISTRO/USUARIO");
		pnlConsultanteFila1.addComponent(txtRegistro);
		
		// lblAplicativo
		lblAplicativo = new Label();
		lblAplicativo.setImmediate(false);
		lblAplicativo.setWidth("130px");
		lblAplicativo.setHeight("-1px");
		lblAplicativo.setValue("APLICATIVO ORIGEN:");
		pnlConsultanteFila1.addComponent(lblAplicativo);
		
		// cmbAplicativo
		cmbAplicativo = new ComboBox();
		cmbAplicativo.setImmediate(false);
		cmbAplicativo.setWidth("100px");
		cmbAplicativo.setHeight("-1px");
		pnlConsultanteFila1.addComponent(cmbAplicativo);
		
		return pnlConsultanteFila1;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteFila2() {
		// common part: create layout
		pnlConsultanteFila2 = new HorizontalLayout();
		pnlConsultanteFila2.setImmediate(false);
		pnlConsultanteFila2.setWidth("-1px");
		pnlConsultanteFila2.setHeight("-1px");
		pnlConsultanteFila2.setMargin(false);
		pnlConsultanteFila2.setSpacing(true);
		
		// lblTipoDOI
		lblTipoDOI = new Label();
		lblTipoDOI.setImmediate(false);
		lblTipoDOI.setWidth("130px");
		lblTipoDOI.setHeight("-1px");
		lblTipoDOI.setValue("TIPO DOI:");
		pnlConsultanteFila2.addComponent(lblTipoDOI);
		
		// cmbTipoDOI
		cmbTipoDOI = new ComboBox();
		cmbTipoDOI.setImmediate(false);
		cmbTipoDOI.setWidth("100px");
		cmbTipoDOI.setHeight("-1px");
		pnlConsultanteFila2.addComponent(cmbTipoDOI);
		
		// lblNumero
		lblNumero = new Label();
		lblNumero.setImmediate(false);
		lblNumero.setWidth("130px");
		lblNumero.setHeight("-1px");
		lblNumero.setValue("NUMERO DOI:");
		pnlConsultanteFila2.addComponent(lblNumero);
		
		// txtNumero
		txtNumero = new TextField();
		txtNumero.setImmediate(false);
		txtNumero.setWidth("100px");
		txtNumero.setHeight("-1px");
		txtNumero.setInputPrompt("NUMERO DOI");
		pnlConsultanteFila2.addComponent(txtNumero);
		
		return pnlConsultanteFila2;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteFila3() {
		// common part: create layout
		pnlConsultanteFila3 = new HorizontalLayout();
		pnlConsultanteFila3.setImmediate(false);
		pnlConsultanteFila3.setWidth("-1px");
		pnlConsultanteFila3.setHeight("-1px");
		pnlConsultanteFila3.setMargin(false);
		pnlConsultanteFila3.setSpacing(true);
		
		// lblPaterno
		lblPaterno = new Label();
		lblPaterno.setImmediate(false);
		lblPaterno.setWidth("130px");
		lblPaterno.setHeight("-1px");
		lblPaterno.setValue("AP. PATERNO:");
		pnlConsultanteFila3.addComponent(lblPaterno);
		
		// txtPaterno
		txtPaterno = new TextField();
		txtPaterno.setImmediate(false);
		txtPaterno.setWidth("100px");
		txtPaterno.setHeight("-1px");
		txtPaterno.setInputPrompt("AP. PATERNO");
		pnlConsultanteFila3.addComponent(txtPaterno);
		
		// lblMaterno
		lblMaterno = new Label();
		lblMaterno.setImmediate(false);
		lblMaterno.setWidth("130px");
		lblMaterno.setHeight("-1px");
		lblMaterno.setValue("AP. MATERNO:");
		pnlConsultanteFila3.addComponent(lblMaterno);
		
		// txtMaterno
		txtMaterno = new TextField();
		txtMaterno.setImmediate(false);
		txtMaterno.setWidth("100px");
		txtMaterno.setHeight("-1px");
		txtMaterno.setInputPrompt("AP. MATERNO");
		pnlConsultanteFila3.addComponent(txtMaterno);
		
		return pnlConsultanteFila3;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteFila4() {
		// common part: create layout
		pnlConsultanteFila4 = new HorizontalLayout();
		pnlConsultanteFila4.setImmediate(false);
		pnlConsultanteFila4.setWidth("-1px");
		pnlConsultanteFila4.setHeight("-1px");
		pnlConsultanteFila4.setMargin(false);
		pnlConsultanteFila4.setSpacing(true);
		
		// lblNombres
		lblNombres = new Label();
		lblNombres.setImmediate(false);
		lblNombres.setWidth("130px");
		lblNombres.setHeight("-1px");
		lblNombres.setValue("NOMBRES:");
		pnlConsultanteFila4.addComponent(lblNombres);
		
		// txtNombres
		txtNombres = new TextField();
		txtNombres.setImmediate(false);
		txtNombres.setWidth("100px");
		txtNombres.setHeight("-1px");
		txtNombres.setInputPrompt("NOMBRES");
		pnlConsultanteFila4.addComponent(txtNombres);
		
		// lblFecha
		lblFecha = new Label();
		lblFecha.setImmediate(false);
		lblFecha.setWidth("130px");
		lblFecha.setHeight("-1px");
		lblFecha.setValue("FEC. NACIMIENTO:");
		pnlConsultanteFila4.addComponent(lblFecha);
		
		// pdfFecha
		pdfFecha = new PopupDateField();
		pdfFecha.setImmediate(false);
		pdfFecha.setWidth("100px");
		pdfFecha.setHeight("-1px");
		pdfFecha.setInvalidAllowed(false);
		pdfFecha.setResolution(4);
		pnlConsultanteFila4.addComponent(pdfFecha);
		
		return pnlConsultanteFila4;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteFila5() {
		// common part: create layout
		pnlConsultanteFila5 = new HorizontalLayout();
		pnlConsultanteFila5.setImmediate(false);
		pnlConsultanteFila5.setWidth("-1px");
		pnlConsultanteFila5.setHeight("-1px");
		pnlConsultanteFila5.setMargin(false);
		pnlConsultanteFila5.setSpacing(true);
		
		// lblCodigo
		lblCodigo = new Label();
		lblCodigo.setImmediate(false);
		lblCodigo.setWidth("130px");
		lblCodigo.setHeight("-1px");
		lblCodigo.setValue("CÓDIGO/DNI:");
		pnlConsultanteFila5.addComponent(lblCodigo);
		
		// txtCodigo
		txtCodigo = new TextField();
		txtCodigo.setImmediate(false);
		txtCodigo.setWidth("100px");
		txtCodigo.setHeight("-1px");
		txtCodigo.setInputPrompt("CÓDIGO/DNI");
		pnlConsultanteFila5.addComponent(txtCodigo);
		
		// lblNacionalidad
		lblNacionalidad = new Label();
		lblNacionalidad.setImmediate(false);
		lblNacionalidad.setWidth("130px");
		lblNacionalidad.setHeight("-1px");
		lblNacionalidad.setValue("NACIONALIDAD:");
		pnlConsultanteFila5.addComponent(lblNacionalidad);
		
		// cmbNacionalidad
		cmbNacionalidad = new ComboBox();
		cmbNacionalidad.setImmediate(false);
		cmbNacionalidad.setWidth("100px");
		cmbNacionalidad.setHeight("-1px");
		pnlConsultanteFila5.addComponent(cmbNacionalidad);
		
		return pnlConsultanteFila5;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteFila6() {
		// common part: create layout
		pnlConsultanteFila6 = new HorizontalLayout();
		pnlConsultanteFila6.setImmediate(false);
		pnlConsultanteFila6.setWidth("-1px");
		pnlConsultanteFila6.setHeight("-1px");
		pnlConsultanteFila6.setMargin(false);
		pnlConsultanteFila6.setSpacing(true);
		
		// lblCentro
		lblCentro = new Label();
		lblCentro.setImmediate(false);
		lblCentro.setWidth("130px");
		lblCentro.setHeight("-1px");
		lblCentro.setValue("CENTRO DE COSTO:");
		pnlConsultanteFila6.addComponent(lblCentro);
		
		// txtCentro
		txtCentro = new TextField();
		txtCentro.setImmediate(false);
		txtCentro.setWidth("100px");
		txtCentro.setHeight("-1px");
		txtCentro.setInputPrompt("CENTRO DE COSTO");
		pnlConsultanteFila6.addComponent(txtCentro);
		
		// lblEstado
		lblEstado = new Label();
		lblEstado.setImmediate(false);
		lblEstado.setWidth("130px");
		lblEstado.setHeight("-1px");
		lblEstado.setValue("ESTADO:");
		pnlConsultanteFila6.addComponent(lblEstado);
		
		// cmbEstado
		cmbEstado = new ComboBox();
		cmbEstado.setImmediate(false);
		cmbEstado.setWidth("100px");
		cmbEstado.setHeight("-1px");
		pnlConsultanteFila6.addComponent(cmbEstado);
		
		return pnlConsultanteFila6;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteFila7() {
		// common part: create layout
		pnlConsultanteFila7 = new HorizontalLayout();
		pnlConsultanteFila7.setImmediate(false);
		pnlConsultanteFila7.setWidth("478px");
		pnlConsultanteFila7.setHeight("-1px");
		pnlConsultanteFila7.setMargin(false);
		pnlConsultanteFila7.setSpacing(true);
		
		// pnlEstadoReniec
		pnlEstadoReniec = buildPnlEstadoReniec();
		pnlConsultanteFila7.addComponent(pnlEstadoReniec);
		pnlConsultanteFila7.setComponentAlignment(pnlEstadoReniec,
				new Alignment(6));
		
		return pnlConsultanteFila7;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlEstadoReniec() {
		// common part: create layout
		pnlEstadoReniec = new HorizontalLayout();
		pnlEstadoReniec.setImmediate(false);
		pnlEstadoReniec.setWidth("-1px");
		pnlEstadoReniec.setHeight("-1px");
		pnlEstadoReniec.setMargin(false);
		pnlEstadoReniec.setSpacing(true);
		
		// lblEstadoReniec
		lblEstadoReniec = new Label();
		lblEstadoReniec.setImmediate(false);
		lblEstadoReniec.setWidth("130px");
		lblEstadoReniec.setHeight("-1px");
		lblEstadoReniec.setValue("ESTADO RENIEC:");
		pnlEstadoReniec.addComponent(lblEstadoReniec);
		
		// cmbEstadoReniec
		cmbEstadoReniec = new ComboBox();
		cmbEstadoReniec.setImmediate(false);
		cmbEstadoReniec.setWidth("100px");
		cmbEstadoReniec.setHeight("-1px");
		pnlEstadoReniec.addComponent(cmbEstadoReniec);
		
		return pnlEstadoReniec;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlConsultanteBoton() {
		// common part: create layout
		pnlConsultanteBoton = new HorizontalLayout();
		pnlConsultanteBoton.setImmediate(false);
		pnlConsultanteBoton.setWidth("480px");
		pnlConsultanteBoton.setHeight("-1px");
		pnlConsultanteBoton.setMargin(false);
		
		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("GUARDAR");
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("-1px");
		btnGuardar.setHeight("-1px");
		pnlConsultanteBoton.addComponent(btnGuardar);
		pnlConsultanteBoton
				.setComponentAlignment(btnGuardar, new Alignment(20));
		
		// btnEstadoReniec
		btnEstadoReniec = new Button();
		btnEstadoReniec.setCaption("ESTADO RENIEC");
		btnEstadoReniec.setImmediate(true);
		btnEstadoReniec.setWidth("-1px");
		btnEstadoReniec.setHeight("-1px");
		pnlConsultanteBoton.addComponent(btnEstadoReniec);
		pnlConsultanteBoton.setComponentAlignment(btnEstadoReniec,
				new Alignment(20));
		
		return pnlConsultanteBoton;
	}

}
