package pe.com.bbva.reniec.ui;

import java.util.Arrays;
import java.util.List;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;

import pe.com.bbva.reniec.dominio.Lista;
import pe.com.bbva.reniec.dominio.Parametro;
import pe.com.bbva.reniec.dominio.Valor;
import pe.com.bbva.reniec.negocio.ConfiguracionService;
import pe.com.bbva.reniec.utileria.BeanValidar;
import pe.com.bbva.reniec.utileria.Constante;
import pe.com.bbva.reniec.utileria.Inject;
import pe.com.bbva.reniec.utileria.ReniecUtil;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.ui.AbstractTextField.TextChangeEventMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class ListasYValoresUI extends CustomComponent implements TextChangeListener, ClickListener{

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout pnlValorContenido;

	@AutoGenerated
	private VerticalLayout pnlGrabarValor;

	@AutoGenerated
	private HorizontalLayout pnlValorFila5;

	@AutoGenerated
	private Button btnEliminarValor;

	@AutoGenerated
	private Button btnGrabarValor;

	@AutoGenerated
	private HorizontalLayout pnlValorFila4;

	@AutoGenerated
	private TextField txtDescripcionValor;

	@AutoGenerated
	private HorizontalLayout pnlValorFila3;

	@AutoGenerated
	private TextField txtOrdenValor;

	@AutoGenerated
	private TextField txtNombreValor;

	@AutoGenerated
	private HorizontalLayout pnlValorFila2;

	@AutoGenerated
	private ComboBox cboEstadoValor;

	@AutoGenerated
	private TextField txtCodigoValor;

	@AutoGenerated
	private TextField lblIdValor;

	@AutoGenerated
	private HorizontalLayout pnlValorFila1;

	@AutoGenerated
	private ComboBox cboLista;

	@AutoGenerated
	private Label lblGrabarValor;

	@AutoGenerated
	private VerticalLayout pnlValores;

	@AutoGenerated
	private Table tblValores;

	@AutoGenerated
	private HorizontalLayout pnlFiltroValores;

	@AutoGenerated
	private TextField txtFiltroEstadoValor;

	@AutoGenerated
	private TextField txtFiltroOrdenValor;

	@AutoGenerated
	private TextField txtFiltroNombreValor;

	@AutoGenerated
	private TextField txtFiltroCodigoValor;

	@AutoGenerated
	private TextField txtFiltroIdValor;

	@AutoGenerated
	private Label lblValores;

	@AutoGenerated
	private HorizontalLayout pnlListaContenido;

	@AutoGenerated
	private VerticalLayout pnlGrabarLista;

	@AutoGenerated
	private HorizontalLayout pnlListaFila4;

	@AutoGenerated
	private Button btnEliminarLista;

	@AutoGenerated
	private Button btnGrabarLista;

	@AutoGenerated
	private VerticalLayout pnlListaFila3;

	@AutoGenerated
	private TextField txtDescripcionLista;

	@AutoGenerated
	private VerticalLayout pnlListaFila2;

	@AutoGenerated
	private TextField txtNombreLista;

	@AutoGenerated
	private HorizontalLayout pnlListaFila1;

	@AutoGenerated
	private ComboBox cbmEstadoLista;

	@AutoGenerated
	private TextField txtCodigoLista;

	@AutoGenerated
	private TextField lblIdLista;

	@AutoGenerated
	private Label lblGrabarLista;

	@AutoGenerated
	private VerticalLayout pnlListas;

	@AutoGenerated
	private Table tblListas;

	@AutoGenerated
	private HorizontalLayout pnlFiltrosListas;

	@AutoGenerated
	private TextField txtFiltroEstadoLista;

	@AutoGenerated
	private TextField txtFiltroNombreLista;

	@AutoGenerated
	private TextField txtFiltroCodigoLista;

	@AutoGenerated
	private TextField txtFiltroIdLista;

	@AutoGenerated
	private Label lblListas;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@Autowired
	ConfiguracionService configuracionService;
	
	public ListasYValoresUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		Inject.inject(this);
		postConstruct();
		debugId();
	}
	
	private void debugId(){
		/*mainLayout.setDebugId("mainLayout");
		pnlValorContenido.setDebugId("pnlValorContenido");
		pnlGrabarValor.setDebugId("pnlGrabarValor");
		pnlValorFila5.setDebugId("pnlValorFila5");
		btnEliminarValor.setDebugId("btnEliminarValor");
		btnGrabarValor.setDebugId("btnGrabarValor");
		pnlValorFila4.setDebugId("pnlValorFila4");
		txtDescripcionValor.setDebugId("txtDescripcionValor");
		pnlValorFila3.setDebugId("pnlValorFila3");
		txtOrdenValor.setDebugId("txtOrdenValor");
		txtNombreValor.setDebugId("txtNombreValor");
		pnlValorFila2.setDebugId("pnlValorFila2");
		cboEstadoValor.setDebugId("cboEstadoValor");
		txtCodigoValor.setDebugId("txtCodigoValor");
		lblIdValor.setDebugId("lblIdValor");
		pnlValorFila1.setDebugId("pnlValorFila1");
		cboLista.setDebugId("cboLista");
		lblGrabarValor.setDebugId("lblGrabarValor");
		pnlValores.setDebugId("pnlValores");
		tblValores.setDebugId("tblValores");
		pnlFiltroValores.setDebugId("pnlFiltroValores");
		txtFiltroEstadoValor.setDebugId("txtFiltroEstadoValor");
		txtFiltroNombreValor.setDebugId("txtFiltroNombreValor");
		txtFiltroCodigoValor.setDebugId("txtFiltroCodigoValor");
		txtFiltroOrdenValor.setDebugId("txtFiltroOrdenValor");
		txtFiltroIdValor.setDebugId("txtFiltroIdValor");
		lblValores.setDebugId("lblValores");
		pnlListaContenido.setDebugId("pnlListaContenido");
		pnlGrabarLista.setDebugId("pnlGrabarLista");
		pnlListaFila4.setDebugId("pnlListaFila4");
		btnEliminarLista.setDebugId("btnEliminarLista");
		btnGrabarLista.setDebugId("btnGrabarLista");
		pnlListaFila3.setDebugId("pnlListaFila3");
		txtDescirpcionLista.setDebugId("txtDescirpcionLista");
		pnlListaFila2.setDebugId("pnlListaFila2");
		txtNombreLista.setDebugId("txtNombreLista");
		pnlListaFila1.setDebugId("pnlListaFila1");
		cbmEstadoLista.setDebugId("cbmEstadoLista");
		txtCodigoLista.setDebugId("txtCodigoLista");
		lblIdLista.setDebugId("lblIdLista");
		lblGrabarLista.setDebugId("lblGrabarLista");
		pnlListas.setDebugId("pnlListas");
		tblListas.setDebugId("tblListas");
		pnlFiltrosListas.setDebugId("pnlFiltrosListas");
		txtFiltroEstadoLista.setDebugId("txtFiltroEstadoLista");
		txtFiltroNombreLista.setDebugId("txtFiltroNombreLista");
		txtFiltroCodigoLista.setDebugId("txtFiltroCodigoLista");
		txtFiltroIdLista.setDebugId("txtFiltroIdLista");
		lblListas.setDebugId("lblListas");*/
	}
	
	public void postConstruct() {	
		
		lblIdLista.setValue("");
		txtDescripcionLista.setNullRepresentation("");
		txtOrdenValor.setNullRepresentation("");
		txtDescripcionValor.setNullRepresentation("");
		txtOrdenValor.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtOrdenValor.addListener(new TextChangeListener() {
			private static final long serialVersionUID = -290756895950492262L;
			@Override
			public void textChange(TextChangeEvent event) {
				if(StringUtils.isNumeric(event.getText())){
					txtOrdenValor.setValue(event.getText());
				}else{
					txtOrdenValor.setValue(txtOrdenValor.getValue());
				}
			}
		});
		pnlValorContenido.setVisible(false);
		List<Lista> listas = configuracionService.buscarListas(null);
		cargarListas(listas);
		
		tblListas.setSelectable(true);
		tblListas.setImmediate(true);
		tblListas.setNullSelectionAllowed(true);
		tblListas.setNullSelectionItemId(null);
		tblListas.addListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent event) {
				if(tblListas.getValue() == null){
					tblListas.setValue(null);
					lblIdLista.setValue("");
					btnGrabarLista.setCaption("Crear");
					limpiar("lista");
					pnlValorContenido.setVisible(false);
				}
				else
				{
					Item item = tblListas.getItem(tblListas.getValue());
					lblIdLista.setValue(item.getItemProperty("id").getValue().toString());
					txtCodigoLista.setValue(item.getItemProperty("codigo").getValue());
					txtNombreLista.setValue(item.getItemProperty("nombre").getValue());
					txtDescripcionLista.setValue(item.getItemProperty("descripcion").getValue());
					cbmEstadoLista.select(item.getItemProperty("estado").getValue());
					
					Lista lista = new Lista();
					lista.setId((Long)item.getItemProperty("id").getValue());
					lista.setCodigo((String)item.getItemProperty("codigo").getValue());
					
					cboLista.select(lista);
					
					Valor valor = new Valor();
					valor.setLista(lista);
					List<Valor> valores = configuracionService.buscarValores(valor);
					cargarValores(valores);
					
					btnGrabarLista.setCaption("Actualizar");
					
					pnlValorContenido.setVisible(true);
					
				}
			}
		});
		tblValores.setSelectable(true);
		tblValores.setImmediate(true);
		tblValores.setNullSelectionAllowed(true);
		tblValores.setNullSelectionItemId(null);
		
		tblValores.addListener(new ValueChangeListener() {
			
			private static final long serialVersionUID = 8766174414524651740L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				if(tblValores.getValue() == null){
					tblValores.setValue(null);
					lblIdValor.setValue("");
					btnGrabarValor.setCaption("Crear");
					limpiar("valor");
				}
				else
				{
					Item item = tblValores.getItem(tblValores.getValue());
					lblIdValor.setValue(item.getItemProperty("id").getValue().toString());
					txtCodigoValor.setValue(item.getItemProperty("codigo").getValue());
					txtNombreValor.setValue(item.getItemProperty("nombre").getValue());
					txtOrdenValor.setValue(item.getItemProperty("orden").getValue());
					txtDescripcionValor.setValue(item.getItemProperty("descripcion").getValue());
					cboEstadoValor.select(item.getItemProperty("estado").getValue());
					
					Lista lista = new Lista();
					lista.setCodigo((String)item.getItemProperty("lista.codigo").getValue());
					lista.setId((Long)item.getItemProperty("lista.id").getValue());
					cboLista.select(lista);
					
					btnGrabarValor.setCaption("Actualizar");
				}
			}
		});
		
		Parametro parametro = configuracionService.obtenerParametroxCodigo(Constante.PARAMETRO.ESTADO_LOV);
		String estados[] = parametro.getValor().split(",");
		BeanItemContainer<String> bicEstados = new BeanItemContainer<String>(String.class, Arrays.asList(estados));
		BeanItemContainer<Lista> bicListas = new BeanItemContainer<Lista>(Lista.class,  listas);
		
		cbmEstadoLista.setInputPrompt("Estado");
		cbmEstadoLista.setContainerDataSource(bicEstados);

		cboEstadoValor.setInputPrompt("Estado");
		cboEstadoValor.setContainerDataSource(bicEstados);
		
		cboLista.setInputPrompt("Lista");
		cboLista.setContainerDataSource(bicListas);
		cboLista.setItemCaptionPropertyId("nombre");
		
		txtFiltroIdLista.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtFiltroCodigoLista.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtFiltroNombreLista.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtFiltroEstadoLista.setTextChangeEventMode(TextChangeEventMode.EAGER);
		
		txtFiltroIdLista.addListener((TextChangeListener)this);
		txtFiltroCodigoLista.addListener((TextChangeListener)this);
		txtFiltroNombreLista.addListener((TextChangeListener)this);
		txtFiltroEstadoLista.addListener((TextChangeListener)this);
		
		txtFiltroIdValor.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtFiltroCodigoValor.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtFiltroNombreValor.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtFiltroEstadoValor.setTextChangeEventMode(TextChangeEventMode.EAGER);
		txtFiltroOrdenValor.setTextChangeEventMode(TextChangeEventMode.EAGER);
		
		txtFiltroIdValor.addListener((TextChangeListener)this);
		txtFiltroCodigoValor.addListener((TextChangeListener)this);
		txtFiltroNombreValor.addListener((TextChangeListener)this);
		txtFiltroEstadoValor.addListener((TextChangeListener)this);
		txtFiltroOrdenValor.addListener((TextChangeListener)this);
		
		btnGrabarLista.addListener((ClickListener)this);
		btnGrabarLista.setCaption("Crear");
		btnEliminarLista.addListener((ClickListener)this);
		btnGrabarValor.addListener((ClickListener)this);
		btnGrabarValor.setCaption("Crear");
		btnEliminarValor.addListener((ClickListener)this);
		
	}
	
	private void limpiar(String nombre)
	{
		if(nombre.equals("lista")){
			txtCodigoLista.setValue("");
			cbmEstadoLista.setValue(null);		
			txtNombreLista.setValue("");
			txtDescripcionLista.setValue("");
		}else if(nombre.equals("valor")){
			txtCodigoValor.setValue("");
			cboEstadoValor.setValue(null);		
			txtNombreValor.setValue("");
			txtDescripcionValor.setValue("");
			txtOrdenValor.setValue("");
			Item item = tblListas.getItem(tblListas.getValue());
			Lista lista = new Lista();
			lista.setId((Long)item.getItemProperty("id").getValue());
			cboLista.select(lista);
		}
	}
	
	private void cargarListas(List<Lista> listas)
	{
		
		IndexedContainer container = new IndexedContainer();
		
		container.addContainerProperty("id", Long.class,  null);
		container.addContainerProperty("codigo", String.class, null);
		container.addContainerProperty("nombre", String.class, null);			
		container.addContainerProperty("descripcion", String.class, null);
		container.addContainerProperty("estado", String.class, null);
		
		int con=1;
		for (Lista lista: listas) {
			Item item = container.addItem(con++);
            item.getItemProperty("id").setValue(lista.getId());
            item.getItemProperty("codigo").setValue(lista.getCodigo());
            item.getItemProperty("nombre").setValue(lista.getNombre());
            item.getItemProperty("descripcion").setValue(lista.getDescripcion());
            item.getItemProperty("estado").setValue(lista.getEstado());
		}
		
		tblListas.setContainerDataSource(container);
		tblListas.setVisibleColumns(new Object[]{"id", "codigo", "nombre", "estado"});
		tblListas.setColumnWidth("id", 16);
		tblListas.setColumnWidth("codigo", 147);
		tblListas.setColumnWidth("nombre", 218);
		tblListas.setColumnWidth("estado", 45);
		tblListas.setColumnHeader("id", "ID");
		tblListas.setColumnHeader("codigo", "Codigo");
		tblListas.setColumnHeader("nombre", "Nombre");
		tblListas.setColumnHeader("estado", "Estado");
		
	}
	
	private void cargarValores(List<Valor> valores)
	{
		IndexedContainer container = new IndexedContainer();
		
		container.addContainerProperty("id", Long.class,  null);
		container.addContainerProperty("codigo", String.class, null);
		container.addContainerProperty("nombre", String.class, null);	
		container.addContainerProperty("orden", Integer.class, null);	
		container.addContainerProperty("descripcion", String.class, null);
		container.addContainerProperty("estado", String.class, null);
		container.addContainerProperty("lista.codigo", String.class, null);
		container.addContainerProperty("lista.id", Long.class, null);
		
		int con=1;
		for (Valor valor: valores) {
			Item item = container.addItem(con++);
            item.getItemProperty("id").setValue(valor.getId());
            item.getItemProperty("codigo").setValue(valor.getCodigo());
            item.getItemProperty("nombre").setValue(valor.getNombre());
            item.getItemProperty("orden").setValue(valor.getOrden());
            item.getItemProperty("descripcion").setValue(valor.getDescripcion());
            item.getItemProperty("estado").setValue(valor.getEstado());
            item.getItemProperty("lista.codigo").setValue(valor.getLista().getCodigo());
            item.getItemProperty("lista.id").setValue(valor.getLista().getId());
		}
		
		tblValores.setContainerDataSource(container);
		tblValores.setVisibleColumns(new Object[]{"id", "codigo", "nombre", "orden", "estado"});
		tblValores.setColumnWidth("id", 16);
		tblValores.setColumnWidth("codigo", 147);
		tblValores.setColumnWidth("nombre", 167);
		tblValores.setColumnWidth("orden", 38);
		tblValores.setColumnWidth("estado", 45);
		tblValores.setColumnHeader("id", "ID");
		tblValores.setColumnHeader("codigo", "Código");
		tblValores.setColumnHeader("nombre", "Nombre");
		tblValores.setColumnHeader("orden", "Orden");
		tblValores.setColumnHeader("estado", "Estado");
		
	}
	
	@Override
	public void textChange(TextChangeEvent event) {
		Lista lista = null;
		Valor valor = null;
		if(event.getSource().equals(txtFiltroIdLista))
		{
			lista = obtenerListaFiltros();
			lista.setId(null);
			if(StringUtils.isNumeric(event.getText()))
			{
				if(StringUtils.isNotBlank(event.getText())){
					lista.setId(Long.parseLong(event.getText()));
				}
				txtFiltroIdLista.setValue(event.getText());
			}else{
				txtFiltroIdLista.setValue(txtFiltroIdLista.getValue());
			}
		}
		if(event.getSource().equals(txtFiltroCodigoLista))
		{
			lista = obtenerListaFiltros();
			if(StringUtils.isNotBlank(event.getText()))
			{
				lista.setCodigo(event.getText());
			}
		}
		if(event.getSource().equals(txtFiltroNombreLista))
		{
			lista = obtenerListaFiltros();
			if(StringUtils.isNotBlank(event.getText()))
			{
				lista.setNombre(event.getText());
			}
		}
		if(event.getSource().equals(txtFiltroEstadoLista))
		{
			lista = obtenerListaFiltros();
			if(StringUtils.isNotBlank(event.getText()))
			{
				lista.setEstado(event.getText());
			}
		}
		//FILTRO DE LAS TABLAS DE VALOR
		if(event.getSource().equals(txtFiltroIdValor))
		{
			valor = obtenerValorFiltros();
			valor.setId(null);
			if(StringUtils.isNumeric(event.getText()))
			{
				if(StringUtils.isNotBlank(event.getText())){
					valor.setId(Long.parseLong(event.getText()));
				}
				txtFiltroIdValor.setValue(event.getText());
			}else{
				txtFiltroIdValor.setValue(txtFiltroIdValor.getValue());
			}
		}
		if(event.getSource().equals(txtFiltroCodigoValor))
		{
			valor = obtenerValorFiltros();
			if(StringUtils.isNotBlank(event.getText()))
			{
				valor.setCodigo(event.getText());
			}
		}
		if(event.getSource().equals(txtFiltroNombreValor))
		{
			valor = obtenerValorFiltros();
			if(StringUtils.isNotBlank(event.getText()))
			{
				valor.setNombre(event.getText());
			}
		}
		if(event.getSource().equals(txtFiltroEstadoValor))
		{
			valor = obtenerValorFiltros();
			if(StringUtils.isNotBlank(event.getText()))
			{
				valor.setEstado(event.getText());
			}
		}
		if(event.getSource().equals(txtFiltroOrdenValor))
		{
			valor = obtenerValorFiltros();
			if(StringUtils.isNumeric(event.getText()))
			{
				if(StringUtils.isNotBlank(event.getText())){
					valor.setOrden(Integer.parseInt(event.getText()));
				}
				txtFiltroOrdenValor.setValue(event.getText());
			}else{
				txtFiltroOrdenValor.setValue(txtFiltroOrdenValor.getValue());
			}
		}
		if(lista!=null){
			List<Lista> listas = configuracionService.buscarListas(lista);
			cargarListas(listas);
			limpiar("lista");
		}
		if(valor!=null){
			Item item = tblListas.getItem(tblListas.getValue());
			lista = new Lista();
			lista.setId((Long)item.getItemProperty("id").getValue());
			valor.setLista(lista);
			List<Valor> valores = configuracionService.buscarValores(valor);
			cargarValores(valores);
			limpiar("valor");
		}
	}

	private Lista obtenerListaFiltros(){
		Lista lista=new Lista();
		if(StringUtils.isNotBlank(txtFiltroIdLista.getValue().toString()))
		{
			lista.setId(Long.parseLong(txtFiltroIdLista.getValue().toString()));
		}
		if(StringUtils.isNotBlank(txtFiltroCodigoLista.getValue().toString()))
		{
			lista.setCodigo(txtFiltroCodigoLista.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtFiltroNombreLista.getValue().toString()))
		{
			lista.setNombre(txtFiltroNombreLista.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtFiltroEstadoLista.getValue().toString()))
		{
			lista.setEstado(txtFiltroEstadoLista.getValue().toString());
		}
		return lista;
	}
	
	private Valor obtenerValorFiltros(){
		Valor valor=new Valor();
		if(StringUtils.isNotBlank(txtFiltroIdValor.getValue().toString()))
		{
			valor.setId(Long.parseLong(txtFiltroIdValor.getValue().toString()));
		}
		if(StringUtils.isNotBlank(txtFiltroCodigoValor.getValue().toString()))
		{
			valor.setCodigo(txtFiltroCodigoValor.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtFiltroNombreValor.getValue().toString()))
		{
			valor.setNombre(txtFiltroNombreValor.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtFiltroEstadoValor.getValue().toString()))
		{
			valor.setEstado(txtFiltroEstadoValor.getValue().toString());
		}
		if(StringUtils.isNotBlank(txtFiltroOrdenValor.getValue().toString()))
		{
			valor.setOrden(Integer.parseInt(txtFiltroOrdenValor.getValue().toString()));
		}
		return valor;
	}

	private void limpiarListaFiltros(){
		txtFiltroIdLista.setValue("");
		txtFiltroCodigoLista.setValue("");
		txtFiltroNombreLista.setValue("");
		txtFiltroEstadoLista.setValue("");
	}
	
	private void limpiarValorFiltros(){
		txtFiltroIdValor.setValue("");
		txtFiltroCodigoValor.setValue("");
		txtFiltroNombreValor.setValue("");
		txtFiltroEstadoValor.setValue("");
		txtFiltroOrdenValor.setValue("");
	}
	
	@Override
	public void buttonClick(ClickEvent event) {
		if(event.getButton().equals(btnGrabarLista))
		{
			buttonClickGrabarLista();
		}
		if(event.getButton().equals(btnEliminarLista))
		{
			buttonClickEliminarLista();
		}
		if(event.getButton().equals(btnGrabarValor))
		{
			buttonClickGrabarValor();
		}
		if(event.getButton().equals(btnEliminarValor))
		{
			buttonClickEliminarValor();
		}
	}
	
	private void buttonClickGrabarLista(){

		Lista lista = new Lista();
		if(StringUtils.isNotBlank((String)lblIdLista.getValue())){
			lista.setId(Long.parseLong(lblIdLista.getValue().toString()));
		}
		lista.setCodigo((String)txtCodigoLista.getValue());
		lista.setNombre((String)txtNombreLista.getValue());
		lista.setDescripcion((String)txtDescripcionLista.getValue());
		lista.setEstado((String)cbmEstadoLista.getValue());
		ReniecUtil.validar(getWindow(), lista, 
				new BeanValidar[]{new BeanValidar("codigo", new Object[]{"Codigo"}, txtCodigoLista),
					new BeanValidar("nombre", new Object[]{"Nombre"}, txtNombreLista),
					new BeanValidar("estado", new Object[]{"Estado"}, cbmEstadoLista)});
		configuracionService.guardarLista(lista);
		limpiar("lista");
		btnGrabarLista.setCaption("Crear");
		limpiarListaFiltros();
		List<Lista> listas = configuracionService.buscarListas(null);
		cargarListas(listas);
		
		BeanItemContainer<Lista> bicListas = new BeanItemContainer<Lista>(Lista.class,  listas);
		cboLista.setInputPrompt("Lista");
		cboLista.setContainerDataSource(bicListas);
		cboLista.setItemCaptionPropertyId("nombre");
		
	}
	
	private void buttonClickEliminarLista(){
		if(tblValores.getItemIds().isEmpty()){
			configuracionService.eliminarLista(Long.parseLong(lblIdLista.getValue().toString()));
			limpiar("lista");
			btnGrabarLista.setCaption("Crear");
			limpiarListaFiltros();
			List<Lista> listas = configuracionService.buscarListas(null);
			cargarListas(listas);
			
			BeanItemContainer<Lista> bicListas = new BeanItemContainer<Lista>(Lista.class,  listas);
			cboLista.setInputPrompt("Lista");
			cboLista.setContainerDataSource(bicListas);
			cboLista.setItemCaptionPropertyId("nombre");
		}
	}
	
	private void buttonClickGrabarValor(){

		Valor valor = new Valor();
		if(StringUtils.isNotBlank((String)lblIdValor.getValue())){
			valor.setId(Long.parseLong(lblIdValor.getValue().toString()));
		}
		if(StringUtils.isNotBlank((String)txtCodigoValor.getValue())){
			valor.setCodigo(txtCodigoValor.getValue().toString().trim());
		}
		if(StringUtils.isNotBlank((String)txtNombreValor.getValue())){
			valor.setNombre(txtNombreValor.getValue().toString().trim());
		}
		if(StringUtils.isNotBlank((String)txtDescripcionValor.getValue())){
			valor.setDescripcion(txtDescripcionValor.getValue().toString().trim());
		}
		if(txtOrdenValor.getValue()!=null && !txtOrdenValor.getValue().equals("")){
		valor.setOrden(Integer.parseInt(txtOrdenValor.getValue().toString()));
		}
		valor.setEstado((String)cboEstadoValor.getValue());
		Lista lista = (Lista)cboLista.getValue();
		valor.setLista(lista);
		ReniecUtil.validar(getWindow(), valor, 
				new BeanValidar[]{new BeanValidar("lista", new Object[]{"Lista"}, cboLista),
					new BeanValidar("codigo", new Object[]{"Codigo"}, txtCodigoLista),
					new BeanValidar("nombre", new Object[]{"Nombre"}, txtNombreLista),
					new BeanValidar("estado", new Object[]{"Estado"}, cbmEstadoLista)});
		configuracionService.guardarValor(valor);
		limpiar("valor");
		btnGrabarLista.setCaption("Crear");
		limpiarValorFiltros();
		
		valor=new Valor();
		Item item = tblListas.getItem(tblListas.getValue());
		lista = new Lista();
		lista.setId((Long)item.getItemProperty("id").getValue());
		valor.setLista(lista);
		List<Valor> valores = configuracionService.buscarValores(valor);
		cargarValores(valores);
	}
	
	private void buttonClickEliminarValor(){
		configuracionService.eliminarValor(Long.parseLong(lblIdValor.getValue().toString()));
		limpiar("valor");
		btnGrabarLista.setCaption("Crear");
		limpiarValorFiltros();
		Valor valor=new Valor();
		Item item = tblListas.getItem(tblListas.getValue());
		Lista lista = new Lista();
		lista.setId((Long)item.getItemProperty("id").getValue());
		valor.setLista(lista);
		List<Valor> valores = configuracionService.buscarValores(valor);
		cargarValores(valores);
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// pnlListaContenido
		pnlListaContenido = buildPnlListaContenido();
		mainLayout.addComponent(pnlListaContenido);
		
		// pnlValorContenido
		pnlValorContenido = buildPnlValorContenido();
		mainLayout.addComponent(pnlValorContenido);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlListaContenido() {
		// common part: create layout
		pnlListaContenido = new HorizontalLayout();
		pnlListaContenido.setImmediate(false);
		pnlListaContenido.setWidth("870px");
		pnlListaContenido.setHeight("-1px");
		pnlListaContenido.setMargin(false);
		
		// pnlListas
		pnlListas = buildPnlListas();
		pnlListaContenido.addComponent(pnlListas);
		
		// pnlGrabarLista
		pnlGrabarLista = buildPnlGrabarLista();
		pnlListaContenido.addComponent(pnlGrabarLista);
		
		return pnlListaContenido;
	}

	@AutoGenerated
	private VerticalLayout buildPnlListas() {
		// common part: create layout
		pnlListas = new VerticalLayout();
		pnlListas.setImmediate(false);
		pnlListas.setWidth("520px");
		pnlListas.setHeight("-1px");
		pnlListas.setMargin(false);
		
		// lblListas
		lblListas = new Label();
		lblListas.setImmediate(false);
		lblListas.setWidth("100.0%");
		lblListas.setHeight("-1px");
		lblListas.setValue("Consulta Listas");
		pnlListas.addComponent(lblListas);
		
		// pnlFiltrosListas
		pnlFiltrosListas = buildPnlFiltrosListas();
		pnlListas.addComponent(pnlFiltrosListas);
		
		// tblListas
		tblListas = new Table();
		tblListas.setImmediate(false);
		tblListas.setWidth("500px");
		tblListas.setHeight("180px");
		pnlListas.addComponent(tblListas);
		
		return pnlListas;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlFiltrosListas() {
		// common part: create layout
		pnlFiltrosListas = new HorizontalLayout();
		pnlFiltrosListas.setImmediate(false);
		pnlFiltrosListas.setWidth("-1px");
		pnlFiltrosListas.setHeight("-1px");
		pnlFiltrosListas.setMargin(false);
		
		// txtFiltroIdLista
		txtFiltroIdLista = new TextField();
		txtFiltroIdLista.setImmediate(false);
		txtFiltroIdLista.setDescription("ID Lista");
		txtFiltroIdLista.setWidth("30px");
		txtFiltroIdLista.setHeight("-1px");
		txtFiltroIdLista.setInputPrompt("ID");
		pnlFiltrosListas.addComponent(txtFiltroIdLista);
		
		// txtFiltroCodigoLista
		txtFiltroCodigoLista = new TextField();
		txtFiltroCodigoLista.setImmediate(false);
		txtFiltroCodigoLista.setWidth("160px");
		txtFiltroCodigoLista.setHeight("-1px");
		txtFiltroCodigoLista.setInputPrompt("Código");
		pnlFiltrosListas.addComponent(txtFiltroCodigoLista);
		
		// txtFiltroNombreLista
		txtFiltroNombreLista = new TextField();
		txtFiltroNombreLista.setImmediate(false);
		txtFiltroNombreLista.setWidth("230px");
		txtFiltroNombreLista.setHeight("-1px");
		txtFiltroNombreLista.setInputPrompt("Nombre");
		pnlFiltrosListas.addComponent(txtFiltroNombreLista);
		
		// txtFiltroEstadoLista
		txtFiltroEstadoLista = new TextField();
		txtFiltroEstadoLista.setImmediate(false);
		txtFiltroEstadoLista.setWidth("60px");
		txtFiltroEstadoLista.setHeight("-1px");
		txtFiltroEstadoLista.setInputPrompt("Estado");
		pnlFiltrosListas.addComponent(txtFiltroEstadoLista);
		
		return pnlFiltrosListas;
	}

	@AutoGenerated
	private VerticalLayout buildPnlGrabarLista() {
		// common part: create layout
		pnlGrabarLista = new VerticalLayout();
		pnlGrabarLista.setImmediate(false);
		pnlGrabarLista.setWidth("350px");
		pnlGrabarLista.setHeight("-1px");
		pnlGrabarLista.setMargin(false);
		
		// lblGrabarLista
		lblGrabarLista = new Label();
		lblGrabarLista.setImmediate(false);
		lblGrabarLista.setWidth("100.0%");
		lblGrabarLista.setHeight("-1px");
		lblGrabarLista.setValue("Grabar Lista");
		pnlGrabarLista.addComponent(lblGrabarLista);
		
		// pnlListaFila1
		pnlListaFila1 = buildPnlListaFila1();
		pnlGrabarLista.addComponent(pnlListaFila1);
		
		// pnlListaFila2
		pnlListaFila2 = buildPnlListaFila2();
		pnlGrabarLista.addComponent(pnlListaFila2);
		
		// pnlListaFila3
		pnlListaFila3 = buildPnlListaFila3();
		pnlGrabarLista.addComponent(pnlListaFila3);
		
		// pnlListaFila4
		pnlListaFila4 = buildPnlListaFila4();
		pnlGrabarLista.addComponent(pnlListaFila4);
		
		return pnlGrabarLista;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlListaFila1() {
		// common part: create layout
		pnlListaFila1 = new HorizontalLayout();
		pnlListaFila1.setImmediate(false);
		pnlListaFila1.setWidth("-1px");
		pnlListaFila1.setHeight("-1px");
		pnlListaFila1.setMargin(false);
		pnlListaFila1.setSpacing(true);
		
		// lblIdLista
		lblIdLista = new TextField();
		lblIdLista.setEnabled(false);
		lblIdLista.setImmediate(false);
		lblIdLista.setWidth("40px");
		lblIdLista.setHeight("-1px");
		pnlListaFila1.addComponent(lblIdLista);
		
		// txtCodigoLista
		txtCodigoLista = new TextField();
		txtCodigoLista.setStyleName("fieldRequired");
		txtCodigoLista.setImmediate(false);
		txtCodigoLista.setWidth("120px");
		txtCodigoLista.setHeight("-1px");
		txtCodigoLista.setInputPrompt("Código");
		pnlListaFila1.addComponent(txtCodigoLista);
		
		// cbmEstadoLista
		cbmEstadoLista = new ComboBox();
		cbmEstadoLista.setImmediate(false);
		cbmEstadoLista.setWidth("150px");
		cbmEstadoLista.setHeight("-1px");
		pnlListaFila1.addComponent(cbmEstadoLista);
		
		return pnlListaFila1;
	}

	@AutoGenerated
	private VerticalLayout buildPnlListaFila2() {
		// common part: create layout
		pnlListaFila2 = new VerticalLayout();
		pnlListaFila2.setCaption(" ");
		pnlListaFila2.setImmediate(false);
		pnlListaFila2.setWidth("-1px");
		pnlListaFila2.setHeight("-1px");
		pnlListaFila2.setMargin(false);
		
		// txtNombreLista
		txtNombreLista = new TextField();
		txtNombreLista.setStyleName("fieldRequired");
		txtNombreLista.setImmediate(false);
		txtNombreLista.setWidth("320px");
		txtNombreLista.setHeight("-1px");
		txtNombreLista.setInputPrompt("Nombre");
		pnlListaFila2.addComponent(txtNombreLista);
		
		return pnlListaFila2;
	}

	@AutoGenerated
	private VerticalLayout buildPnlListaFila3() {
		// common part: create layout
		pnlListaFila3 = new VerticalLayout();
		pnlListaFila3.setCaption(" ");
		pnlListaFila3.setImmediate(false);
		pnlListaFila3.setWidth("-1px");
		pnlListaFila3.setHeight("-1px");
		pnlListaFila3.setMargin(false);
		
		// txtDescripcionLista
		txtDescripcionLista = new TextField();
		txtDescripcionLista.setImmediate(false);
		txtDescripcionLista.setWidth("320px");
		txtDescripcionLista.setHeight("-1px");
		txtDescripcionLista.setInputPrompt("Descripción");
		pnlListaFila3.addComponent(txtDescripcionLista);
		
		return pnlListaFila3;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlListaFila4() {
		// common part: create layout
		pnlListaFila4 = new HorizontalLayout();
		pnlListaFila4.setCaption(" ");
		pnlListaFila4.setImmediate(false);
		pnlListaFila4.setWidth("320px");
		pnlListaFila4.setHeight("-1px");
		pnlListaFila4.setMargin(false);
		
		// btnGrabarLista
		btnGrabarLista = new Button();
		btnGrabarLista.setCaption("Actualizar");
		btnGrabarLista.setImmediate(true);
		btnGrabarLista.setWidth("-1px");
		btnGrabarLista.setHeight("-1px");
		pnlListaFila4.addComponent(btnGrabarLista);
		pnlListaFila4.setComponentAlignment(btnGrabarLista, new Alignment(20));
		
		// btnEliminarLista
		btnEliminarLista = new Button();
		btnEliminarLista.setCaption("Eliminar");
		btnEliminarLista.setImmediate(true);
		btnEliminarLista.setWidth("-1px");
		btnEliminarLista.setHeight("-1px");
		pnlListaFila4.addComponent(btnEliminarLista);
		pnlListaFila4
				.setComponentAlignment(btnEliminarLista, new Alignment(20));
		
		return pnlListaFila4;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlValorContenido() {
		// common part: create layout
		pnlValorContenido = new HorizontalLayout();
		pnlValorContenido.setImmediate(false);
		pnlValorContenido.setWidth("870px");
		pnlValorContenido.setHeight("-1px");
		pnlValorContenido.setMargin(false);
		
		// pnlValores
		pnlValores = buildPnlValores();
		pnlValorContenido.addComponent(pnlValores);
		
		// pnlGrabarValor
		pnlGrabarValor = buildPnlGrabarValor();
		pnlValorContenido.addComponent(pnlGrabarValor);
		
		return pnlValorContenido;
	}

	@AutoGenerated
	private VerticalLayout buildPnlValores() {
		// common part: create layout
		pnlValores = new VerticalLayout();
		pnlValores.setImmediate(false);
		pnlValores.setWidth("520px");
		pnlValores.setHeight("-1px");
		pnlValores.setMargin(false);
		
		// lblValores
		lblValores = new Label();
		lblValores.setImmediate(false);
		lblValores.setWidth("100.0%");
		lblValores.setHeight("-1px");
		lblValores.setValue("Lista Valores origen");
		pnlValores.addComponent(lblValores);
		
		// pnlFiltroValores
		pnlFiltroValores = buildPnlFiltroValores();
		pnlValores.addComponent(pnlFiltroValores);
		
		// tblValores
		tblValores = new Table();
		tblValores.setImmediate(false);
		tblValores.setWidth("500px");
		tblValores.setHeight("160px");
		pnlValores.addComponent(tblValores);
		
		return pnlValores;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlFiltroValores() {
		// common part: create layout
		pnlFiltroValores = new HorizontalLayout();
		pnlFiltroValores.setImmediate(false);
		pnlFiltroValores.setWidth("-1px");
		pnlFiltroValores.setHeight("-1px");
		pnlFiltroValores.setMargin(false);
		
		// txtFiltroIdValor
		txtFiltroIdValor = new TextField();
		txtFiltroIdValor.setImmediate(false);
		txtFiltroIdValor.setDescription("ID Lista");
		txtFiltroIdValor.setWidth("30px");
		txtFiltroIdValor.setHeight("-1px");
		txtFiltroIdValor.setInputPrompt("ID");
		pnlFiltroValores.addComponent(txtFiltroIdValor);
		
		// txtFiltroCodigoValor
		txtFiltroCodigoValor = new TextField();
		txtFiltroCodigoValor.setImmediate(false);
		txtFiltroCodigoValor.setWidth("160px");
		txtFiltroCodigoValor.setHeight("-1px");
		txtFiltroCodigoValor.setInputPrompt("Código");
		pnlFiltroValores.addComponent(txtFiltroCodigoValor);
		
		// txtFiltroNombreValor
		txtFiltroNombreValor = new TextField();
		txtFiltroNombreValor.setImmediate(false);
		txtFiltroNombreValor.setWidth("180px");
		txtFiltroNombreValor.setHeight("-1px");
		txtFiltroNombreValor.setInputPrompt("Nombre");
		pnlFiltroValores.addComponent(txtFiltroNombreValor);
		
		// txtFiltroOrdenValor
		txtFiltroOrdenValor = new TextField();
		txtFiltroOrdenValor.setImmediate(false);
		txtFiltroOrdenValor.setWidth("50px");
		txtFiltroOrdenValor.setHeight("-1px");
		txtFiltroOrdenValor.setInputPrompt("Orden");
		pnlFiltroValores.addComponent(txtFiltroOrdenValor);
		
		// txtFiltroEstadoValor
		txtFiltroEstadoValor = new TextField();
		txtFiltroEstadoValor.setImmediate(false);
		txtFiltroEstadoValor.setWidth("60px");
		txtFiltroEstadoValor.setHeight("-1px");
		txtFiltroEstadoValor.setInputPrompt("Estado");
		pnlFiltroValores.addComponent(txtFiltroEstadoValor);
		
		return pnlFiltroValores;
	}

	@AutoGenerated
	private VerticalLayout buildPnlGrabarValor() {
		// common part: create layout
		pnlGrabarValor = new VerticalLayout();
		pnlGrabarValor.setImmediate(false);
		pnlGrabarValor.setWidth("350px");
		pnlGrabarValor.setHeight("-1px");
		pnlGrabarValor.setMargin(false);
		
		// lblGrabarValor
		lblGrabarValor = new Label();
		lblGrabarValor.setImmediate(false);
		lblGrabarValor.setWidth("100.0%");
		lblGrabarValor.setHeight("-1px");
		lblGrabarValor.setValue("Grabar Valor");
		pnlGrabarValor.addComponent(lblGrabarValor);
		
		// pnlValorFila1
		pnlValorFila1 = buildPnlValorFila1();
		pnlGrabarValor.addComponent(pnlValorFila1);
		
		// pnlValorFila2
		pnlValorFila2 = buildPnlValorFila2();
		pnlGrabarValor.addComponent(pnlValorFila2);
		
		// pnlValorFila3
		pnlValorFila3 = buildPnlValorFila3();
		pnlGrabarValor.addComponent(pnlValorFila3);
		
		// pnlValorFila4
		pnlValorFila4 = buildPnlValorFila4();
		pnlGrabarValor.addComponent(pnlValorFila4);
		
		// pnlValorFila5
		pnlValorFila5 = buildPnlValorFila5();
		pnlGrabarValor.addComponent(pnlValorFila5);
		
		return pnlGrabarValor;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlValorFila1() {
		// common part: create layout
		pnlValorFila1 = new HorizontalLayout();
		pnlValorFila1.setImmediate(false);
		pnlValorFila1.setWidth("-1px");
		pnlValorFila1.setHeight("-1px");
		pnlValorFila1.setMargin(false);
		
		// cboLista
		cboLista = new ComboBox();
		cboLista.setImmediate(false);
		cboLista.setWidth("320px");
		cboLista.setHeight("-1px");
		pnlValorFila1.addComponent(cboLista);
		
		return pnlValorFila1;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlValorFila2() {
		// common part: create layout
		pnlValorFila2 = new HorizontalLayout();
		pnlValorFila2.setCaption(" ");
		pnlValorFila2.setImmediate(false);
		pnlValorFila2.setWidth("-1px");
		pnlValorFila2.setHeight("-1px");
		pnlValorFila2.setMargin(false);
		pnlValorFila2.setSpacing(true);
		
		// lblIdValor
		lblIdValor = new TextField();
		lblIdValor.setEnabled(false);
		lblIdValor.setImmediate(false);
		lblIdValor.setWidth("40px");
		lblIdValor.setHeight("-1px");
		pnlValorFila2.addComponent(lblIdValor);
		
		// txtCodigoValor
		txtCodigoValor = new TextField();
		txtCodigoValor.setStyleName("fieldRequired");
		txtCodigoValor.setImmediate(false);
		txtCodigoValor.setWidth("120px");
		txtCodigoValor.setHeight("-1px");
		txtCodigoValor.setInputPrompt("Código");
		pnlValorFila2.addComponent(txtCodigoValor);
		
		// cboEstadoValor
		cboEstadoValor = new ComboBox();
		cboEstadoValor.setImmediate(false);
		cboEstadoValor.setWidth("150px");
		cboEstadoValor.setHeight("-1px");
		pnlValorFila2.addComponent(cboEstadoValor);
		
		return pnlValorFila2;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlValorFila3() {
		// common part: create layout
		pnlValorFila3 = new HorizontalLayout();
		pnlValorFila3.setCaption(" ");
		pnlValorFila3.setImmediate(false);
		pnlValorFila3.setWidth("-1px");
		pnlValorFila3.setHeight("-1px");
		pnlValorFila3.setMargin(false);
		pnlValorFila3.setSpacing(true);
		
		// txtNombreValor
		txtNombreValor = new TextField();
		txtNombreValor.setStyleName("fieldRequired");
		txtNombreValor.setImmediate(false);
		txtNombreValor.setWidth("200px");
		txtNombreValor.setHeight("-1px");
		txtNombreValor.setInputPrompt("Nombre");
		pnlValorFila3.addComponent(txtNombreValor);
		pnlValorFila3.setExpandRatio(txtNombreValor, 1.0f);
		
		// txtOrdenValor
		txtOrdenValor = new TextField();
		txtOrdenValor.setImmediate(false);
		txtOrdenValor.setWidth("115px");
		txtOrdenValor.setHeight("-1px");
		txtOrdenValor.setInputPrompt("Orden");
		pnlValorFila3.addComponent(txtOrdenValor);
		
		return pnlValorFila3;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlValorFila4() {
		// common part: create layout
		pnlValorFila4 = new HorizontalLayout();
		pnlValorFila4.setCaption(" ");
		pnlValorFila4.setImmediate(false);
		pnlValorFila4.setWidth("-1px");
		pnlValorFila4.setHeight("-1px");
		pnlValorFila4.setMargin(false);
		
		// txtDescripcionValor
		txtDescripcionValor = new TextField();
		txtDescripcionValor.setImmediate(false);
		txtDescripcionValor.setWidth("320px");
		txtDescripcionValor.setHeight("-1px");
		txtDescripcionValor.setInputPrompt("Descripción");
		pnlValorFila4.addComponent(txtDescripcionValor);
		pnlValorFila4.setExpandRatio(txtDescripcionValor, 1.0f);
		
		return pnlValorFila4;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlValorFila5() {
		// common part: create layout
		pnlValorFila5 = new HorizontalLayout();
		pnlValorFila5.setCaption(" ");
		pnlValorFila5.setImmediate(false);
		pnlValorFila5.setWidth("320px");
		pnlValorFila5.setHeight("-1px");
		pnlValorFila5.setMargin(false);
		
		// btnGrabarValor
		btnGrabarValor = new Button();
		btnGrabarValor.setCaption("Actualizar");
		btnGrabarValor.setImmediate(true);
		btnGrabarValor.setWidth("-1px");
		btnGrabarValor.setHeight("-1px");
		pnlValorFila5.addComponent(btnGrabarValor);
		pnlValorFila5.setComponentAlignment(btnGrabarValor, new Alignment(20));
		
		// btnEliminarValor
		btnEliminarValor = new Button();
		btnEliminarValor.setCaption("Eliminar");
		btnEliminarValor.setImmediate(true);
		btnEliminarValor.setWidth("-1px");
		btnEliminarValor.setHeight("-1px");
		pnlValorFila5.addComponent(btnEliminarValor);
		pnlValorFila5
				.setComponentAlignment(btnEliminarValor, new Alignment(20));
		
		return pnlValorFila5;
	}

}
