package pe.com.bbva.reniec.ui;

import java.util.List;
import java.util.Map;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;

import pe.com.bbva.reniec.dominio.Lista;
import pe.com.bbva.reniec.dominio.Opcion;
import pe.com.bbva.reniec.dominio.Valor;
import pe.com.bbva.reniec.negocio.SeguridadService;
import pe.com.bbva.reniec.utileria.Constante;
import pe.com.bbva.reniec.utileria.Inject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.HierarchicalContainer;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.ui.AbstractTextField.TextChangeEventMode;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;


@SuppressWarnings("serial")
public class OpcionesUI extends CustomComponent implements ClickListener{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout pnlOpcionContenido;
	@AutoGenerated
	private VerticalLayout pnlContenedorGrabar;
	@AutoGenerated
	private HorizontalLayout pnlContenedorFila1;
	@AutoGenerated
	private VerticalLayout pnlGrabarOpcion;
	@AutoGenerated
	private HorizontalLayout pnlOpcionFila4;
	@AutoGenerated
	private Button btnEliminarOpcion;
	@AutoGenerated
	private Button btnGrabarOpcion;
	@AutoGenerated
	private HorizontalLayout pnlOpcionFila3;
	@AutoGenerated
	private ComboBox cmbEstatus;
	@AutoGenerated
	private TextArea txtADescripcionOpcion;
	@AutoGenerated
	private HorizontalLayout pnlOpcionFila2;
	@AutoGenerated
	private ComboBox cmbPadreOpcion;
	@AutoGenerated
	private TextField txtOrdenOpcion;
	@AutoGenerated
	private ComboBox cmbTipoOpcion;
	@AutoGenerated
	private HorizontalLayout pnlOpcionFila1;
	@AutoGenerated
	private TextField txtNombreOpcion;
	@AutoGenerated
	private TextField txtCodigoOpcion;
	@AutoGenerated
	private TextField txtIdOpcion;
	@AutoGenerated
	private Label lblGrabarOpcion;
	@AutoGenerated
	private VerticalLayout pnlOpcion;
	@AutoGenerated
	private Tree treeOpcion;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@Autowired
	private SeguridadService seguridadService;
	
	private boolean flagNuevo;
	
	private Long idOpcion;
	
	public OpcionesUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		Inject.inject(this);
		postConstruct();
		debugId();
	}

	private void debugId(){
		mainLayout.setDebugId("mainLayout");
		pnlOpcionContenido.setDebugId("pnlOpcionContenido");
		pnlContenedorGrabar.setDebugId("pnlContenedorGrabar");
		pnlContenedorFila1.setDebugId("pnlContenedorFila1");
		pnlGrabarOpcion.setDebugId("pnlGrabarOpcion");
		pnlOpcionFila4.setDebugId("pnlOpcionFila4");
		btnEliminarOpcion.setDebugId("btnEliminarOpcion");
		btnGrabarOpcion.setDebugId("btnGrabarOpcion");
		pnlOpcionFila3.setDebugId("pnlOpcionFila3");
		cmbEstatus.setDebugId("cmbEstatus");
		txtADescripcionOpcion.setDebugId("txtADescripcionOpcion");
		pnlOpcionFila2.setDebugId("pnlOpcionFila2");
		cmbPadreOpcion.setDebugId("cmbPadreOpcion");
		txtOrdenOpcion.setDebugId("txtOrdenOpcion");
		cmbTipoOpcion.setDebugId("cmbTipoOpcion");
		pnlOpcionFila1.setDebugId("pnlOpcionFila1");
		txtNombreOpcion.setDebugId("txtNombreOpcion");
		txtCodigoOpcion.setDebugId("txtCodigoOpcion");
		txtIdOpcion.setDebugId("lblIdOpcion");
		lblGrabarOpcion.setDebugId("lblGrabarOpcion");
		pnlOpcion.setDebugId("pnlOpcion");
		treeOpcion.setDebugId("treeOpcion");

	}
	
	public void postConstruct() {
		
		pnlOpcion.setSizeUndefined();
		
		txtIdOpcion.setValue("");
		txtADescripcionOpcion.setNullRepresentation("");
		txtOrdenOpcion.setNullRepresentation("");
		txtOrdenOpcion.addListener(new TextChangeListener() {

			@Override
			public void textChange(TextChangeEvent event) {
				if(StringUtils.isNumeric(event.getText())){
					if(event.getText().length()<=8){
						txtOrdenOpcion.setValue(event.getText());
					}else{
						txtOrdenOpcion.setValue(txtOrdenOpcion.getValue());
					}
				}else{
					txtOrdenOpcion.setValue(txtOrdenOpcion.getValue());
				}
			}
		});
		txtOrdenOpcion.setTextChangeEventMode(TextChangeEventMode.EAGER);
		
		habilitarEdicion(false);
		
		List<Opcion> opciones = seguridadService.buscarOpciones(null);
		BeanItemContainer<Opcion> bicOpciones = new BeanItemContainer<Opcion>(Opcion.class,  opciones);

		cmbPadreOpcion.setInputPrompt("Padre");
		cmbPadreOpcion.setContainerDataSource(bicOpciones);
		cmbPadreOpcion.setItemCaptionPropertyId("nombre");
		
		List<Valor> valores = seguridadService.obtenerValoresxLista(Constante.LISTA.CODIGO.OPCION_TIPO);
		BeanItemContainer<Valor> bicValores = new BeanItemContainer<Valor>(Valor.class,  valores);
		
		cmbTipoOpcion.setInputPrompt("Tipo");
		cmbTipoOpcion.setContainerDataSource(bicValores);
		cmbTipoOpcion.setItemCaptionPropertyId("nombre");
		
		List<Valor> estatus = seguridadService.obtenerValoresxLista(Constante.LISTA.CODIGO.REGISTRO_ESTADO);
		BeanItemContainer<Valor> bicEstatus = new BeanItemContainer<Valor>(Valor.class,  estatus);
		
		cmbEstatus.setInputPrompt("Estado");
		cmbEstatus.setContainerDataSource(bicEstatus);
		cmbEstatus.setItemCaptionPropertyId("nombre");
		
		
		Map<String,List<Opcion>> map = seguridadService.listarOpciones();
		cargarOpciones(map);
		
		treeOpcion.setImmediate(true);
		treeOpcion.addListener(new ValueChangeListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				boolean esModoNuevo = treeOpcion.getValue() == null;
				if(esModoNuevo){
					treeOpcion.setValue(null);
					habilitarEdicion(!esModoNuevo);
					txtIdOpcion.setValue("");
					limpiar();
				}
				else
				{
					Item item = treeOpcion.getItem(treeOpcion.getValue());
					Opcion opcion = null;
					if(item.getItemProperty("padre.id").getValue()!=null){
						opcion = new Opcion();
						opcion.setId((Long)item.getItemProperty("padre.id").getValue());
						opcion.setCodigo((String)item.getItemProperty("padre.codigo").getValue());
					}
					cmbPadreOpcion.select(opcion);
					txtIdOpcion.setValue(item.getItemProperty("id").getValue());
					txtCodigoOpcion.setValue(item.getItemProperty("codigo").getValue());
					txtNombreOpcion.setValue(item.getItemProperty("nombre").getValue());
					txtADescripcionOpcion.setValue(item.getItemProperty("descripcion").getValue());
					txtOrdenOpcion.setValue(item.getItemProperty("orden").getValue());
					Valor tipo = new Valor();
					idOpcion = (Long)item.getItemProperty("id").getValue();
					tipo.setId((Long)item.getItemProperty("tipo.id").getValue());
					tipo.setCodigo((String)item.getItemProperty("tipo.codigo").getValue());
					tipo.setLista(new Lista());
					tipo.getLista().setCodigo((String)item.getItemProperty("tipo.lista.codigo").getValue());
					cmbTipoOpcion.select(tipo);
					
					Valor estatus = new Valor();
					estatus.setId((Long)item.getItemProperty("estatus.id").getValue());
					estatus.setCodigo((String)item.getItemProperty("estatus.codigo").getValue());
					estatus.setLista(new Lista());
					estatus.getLista().setCodigo((String)item.getItemProperty("estatus.lista.codigo").getValue());
					cmbEstatus.select(estatus);

					habilitarEdicion(!esModoNuevo);
					
				}
			}
		});
		
		btnGrabarOpcion.addListener((ClickListener)this);
		btnEliminarOpcion.addListener((ClickListener)this);
		
	}
	
	private void recorrer(String codigo, Map<String, List<Opcion>> map, Long objPadre, HierarchicalContainer hwContainer) {
		Item item = null;
		for (Opcion opc : map.get(codigo)) {
			item = hwContainer.addItem(opc.getId());
			item.getItemProperty("id").setValue(opc.getId());
			item.getItemProperty("padre.id").setValue(opc.getPadre() == null ? null : opc.getPadre().getId());
			item.getItemProperty("padre.codigo").setValue(opc.getPadre() == null ? null : opc.getPadre().getCodigo());
			item.getItemProperty("codigo").setValue(opc.getCodigo());
			item.getItemProperty("nombre").setValue(opc.getNombre());
			item.getItemProperty("descripcion").setValue(opc.getDescripcion());
			item.getItemProperty("orden").setValue(opc.getOrden());
			item.getItemProperty("tipo.id").setValue(opc.getTipo().getId());
			item.getItemProperty("tipo.codigo").setValue(opc.getTipo().getCodigo());
			item.getItemProperty("tipo.lista.codigo").setValue(opc.getTipo().getLista().getCodigo());
			item.getItemProperty("estatus.id").setValue(opc.getEstado().getId());
			item.getItemProperty("estatus.nombre").setValue(opc.getEstado().getNombre());
			item.getItemProperty("estatus.codigo").setValue(opc.getEstado().getCodigo());
			item.getItemProperty("estatus.lista.codigo").setValue(opc.getEstado().getLista().getCodigo());
			
			if (!codigo.equals(Constante.OPCION.KEY_PADRE)) {
				hwContainer.setParent(opc.getId(), objPadre);
			}
			if (map.get(opc.getCodigo()) != null) {
				recorrer(opc.getCodigo(), map, opc.getId(),hwContainer);
			} else {
				hwContainer.setChildrenAllowed(opc.getId(), false);
			}
		}
	}
	
	private void habilitarEdicion(boolean flag)
	{
		flagNuevo = !flag;
		btnEliminarOpcion.setVisible(flag);
		if(flag)
		{
			btnGrabarOpcion.setCaption("Actualizar");
		}
		else
		{
			btnGrabarOpcion.setCaption("Crear");
		}
	}
	
	private void limpiar()
	{
		cmbPadreOpcion.select(null);
		txtIdOpcion.setValue("");
		txtCodigoOpcion.setValue("");
		txtNombreOpcion.setValue("");
		txtADescripcionOpcion.setValue("");
		txtOrdenOpcion.setValue("");
		cmbTipoOpcion.select(null);
		cmbEstatus.select(null);
	}
	
	private void cargarOpciones(Map<String,List<Opcion>> map)
	{
		HierarchicalContainer hwContainer = new HierarchicalContainer();

		hwContainer.addContainerProperty("id", Long.class, null);
		hwContainer.addContainerProperty("padre.id", Long.class, null);
		hwContainer.addContainerProperty("padre.codigo", String.class, null);
		hwContainer.addContainerProperty("codigo", String.class, null);
		hwContainer.addContainerProperty("nombre", String.class, null);
		hwContainer.addContainerProperty("descripcion", String.class, null);
		hwContainer.addContainerProperty("orden", Integer.class, null);
		hwContainer.addContainerProperty("tipo.id", Long.class, null);
		hwContainer.addContainerProperty("tipo.codigo", String.class, null);
		hwContainer.addContainerProperty("tipo.lista.codigo", String.class, null);
		hwContainer.addContainerProperty("estatus.id", Long.class, null);
		hwContainer.addContainerProperty("estatus.codigo", String.class, null);
		hwContainer.addContainerProperty("estatus.nombre", String.class, null);
		hwContainer.addContainerProperty("estatus.lista.codigo", String.class, null);
		
		if(map.get(Constante.OPCION.KEY_PADRE) != null){
			recorrer(Constante.OPCION.KEY_PADRE, map, null, hwContainer);
		}
		treeOpcion.setContainerDataSource(hwContainer);
		treeOpcion.setItemCaptionPropertyId("nombre");
		for (Object id : treeOpcion.rootItemIds()) {
			treeOpcion.expandItemsRecursively(id);
        }
		
	}
	
	@Override
	public void buttonClick(ClickEvent event) {
		if(event.getButton().equals(btnGrabarOpcion))
		{
			buttonClickGrabar();
		}
		else if(event.getButton().equals(btnEliminarOpcion))
		{
			buttonClickEliminar();
		}
	}
	
	private void buttonClickGrabar(){

		Opcion opcion = new Opcion();
		opcion.setPadre((Opcion)cmbPadreOpcion.getValue());
		opcion.setCodigo((String)txtCodigoOpcion.getValue());
		opcion.setNombre((String)txtNombreOpcion.getValue());
		opcion.setDescripcion((String)txtADescripcionOpcion.getValue());
		if(txtOrdenOpcion.getValue()!=null && !txtOrdenOpcion.getValue().equals("")){
			opcion.setOrden(Integer.parseInt(txtOrdenOpcion.getValue().toString()));
		}
		opcion.setTipo((Valor)cmbTipoOpcion.getValue());
		
		opcion.setEstado((Valor)cmbEstatus.getValue());
		
		if(!flagNuevo)
		{
			opcion.setId(Long.parseLong(txtIdOpcion.getValue().toString()));
		}
		seguridadService.guardarOpcion(opcion);
		refrescar();
	
	}
	
	private void buttonClickEliminar(){
		Opcion opcion=new Opcion();
		opcion.setId(Long.parseLong(txtIdOpcion.getValue().toString()));
		seguridadService.eliminarOpcion(Long.parseLong(txtIdOpcion.getValue().toString()));
		refrescar();
	
	}
	
	private void refrescar()
	{
		habilitarEdicion(false);
		limpiar();
		Map<String,List<Opcion>> map = seguridadService.listarOpciones();
		cargarOpciones(map);
		List<Opcion> opciones = seguridadService.buscarOpciones(null);
		BeanItemContainer<Opcion> bicOpciones = new BeanItemContainer<Opcion>(Opcion.class,  opciones);
		cmbPadreOpcion.setInputPrompt("Padre");
		cmbPadreOpcion.setContainerDataSource(bicOpciones);
		cmbPadreOpcion.setItemCaptionPropertyId("nombre");
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// pnlOpcionContenido
		pnlOpcionContenido = buildPnlOpcionContenido();
		mainLayout.addComponent(pnlOpcionContenido);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlOpcionContenido() {
		// common part: create layout
		pnlOpcionContenido = new HorizontalLayout();
		pnlOpcionContenido.setImmediate(false);
		pnlOpcionContenido.setWidth("1000px");
		pnlOpcionContenido.setHeight("-1px");
		pnlOpcionContenido.setMargin(false);
		
		// pnlOpcion
		pnlOpcion = buildPnlOpcion();
		pnlOpcionContenido.addComponent(pnlOpcion);
		
		// pnlContenedorGrabar
		pnlContenedorGrabar = buildPnlContenedorGrabar();
		pnlOpcionContenido.addComponent(pnlContenedorGrabar);
		
		return pnlOpcionContenido;
	}

	@AutoGenerated
	private VerticalLayout buildPnlOpcion() {
		// common part: create layout
		pnlOpcion = new VerticalLayout();
		pnlOpcion.setImmediate(false);
		pnlOpcion.setWidth("-1px");
		pnlOpcion.setHeight("-1px");
		pnlOpcion.setMargin(false);
		
		// treeOpcion
		treeOpcion = new Tree();
		treeOpcion.setImmediate(false);
		treeOpcion.setWidth("-1px");
		treeOpcion.setHeight("-1px");
		pnlOpcion.addComponent(treeOpcion);
		
		return pnlOpcion;
	}

	@AutoGenerated
	private VerticalLayout buildPnlContenedorGrabar() {
		// common part: create layout
		pnlContenedorGrabar = new VerticalLayout();
		pnlContenedorGrabar.setImmediate(false);
		pnlContenedorGrabar.setWidth("-1px");
		pnlContenedorGrabar.setHeight("-1px");
		pnlContenedorGrabar.setMargin(false);
		pnlContenedorGrabar.setSpacing(true);
		
		// pnlContenedorFila1
		pnlContenedorFila1 = buildPnlContenedorFila1();
		pnlContenedorGrabar.addComponent(pnlContenedorFila1);
		
		return pnlContenedorGrabar;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlContenedorFila1() {
		// common part: create layout
		pnlContenedorFila1 = new HorizontalLayout();
		pnlContenedorFila1.setImmediate(false);
		pnlContenedorFila1.setWidth("-1px");
		pnlContenedorFila1.setHeight("-1px");
		pnlContenedorFila1.setMargin(false);
		pnlContenedorFila1.setSpacing(true);
		
		// pnlGrabarOpcion
		pnlGrabarOpcion = buildPnlGrabarOpcion();
		pnlContenedorFila1.addComponent(pnlGrabarOpcion);
		
		return pnlContenedorFila1;
	}

	@AutoGenerated
	private VerticalLayout buildPnlGrabarOpcion() {
		// common part: create layout
		pnlGrabarOpcion = new VerticalLayout();
		pnlGrabarOpcion.setImmediate(false);
		pnlGrabarOpcion.setWidth("-1px");
		pnlGrabarOpcion.setHeight("-1px");
		pnlGrabarOpcion.setMargin(false);
		pnlGrabarOpcion.setSpacing(true);
		
		// lblGrabarOpcion
		lblGrabarOpcion = new Label();
		lblGrabarOpcion.setImmediate(false);
		lblGrabarOpcion.setWidth("-1px");
		lblGrabarOpcion.setHeight("-1px");
		lblGrabarOpcion.setValue("Opción");
		pnlGrabarOpcion.addComponent(lblGrabarOpcion);
		
		// pnlOpcionFila1
		pnlOpcionFila1 = buildPnlOpcionFila1();
		pnlGrabarOpcion.addComponent(pnlOpcionFila1);
		
		// pnlOpcionFila2
		pnlOpcionFila2 = buildPnlOpcionFila2();
		pnlGrabarOpcion.addComponent(pnlOpcionFila2);
		
		// pnlOpcionFila3
		pnlOpcionFila3 = buildPnlOpcionFila3();
		pnlGrabarOpcion.addComponent(pnlOpcionFila3);
		
		// pnlOpcionFila4
		pnlOpcionFila4 = buildPnlOpcionFila4();
		pnlGrabarOpcion.addComponent(pnlOpcionFila4);
		
		return pnlGrabarOpcion;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlOpcionFila1() {
		// common part: create layout
		pnlOpcionFila1 = new HorizontalLayout();
		pnlOpcionFila1.setImmediate(false);
		pnlOpcionFila1.setWidth("-1px");
		pnlOpcionFila1.setHeight("-1px");
		pnlOpcionFila1.setMargin(false);
		pnlOpcionFila1.setSpacing(true);
		
		// txtIdOpcion
		txtIdOpcion = new TextField();
		txtIdOpcion.setEnabled(false);
		txtIdOpcion.setImmediate(false);
		txtIdOpcion.setWidth("40px");
		txtIdOpcion.setHeight("-1px");
		txtIdOpcion.setSecret(false);
		pnlOpcionFila1.addComponent(txtIdOpcion);
		
		// txtCodigoOpcion
		txtCodigoOpcion = new TextField();
		txtCodigoOpcion.setStyleName("fieldRequired");
		txtCodigoOpcion.setImmediate(false);
		txtCodigoOpcion.setWidth("250px");
		txtCodigoOpcion.setHeight("-1px");
		txtCodigoOpcion.setInputPrompt("Código");
		txtCodigoOpcion.setSecret(false);
		pnlOpcionFila1.addComponent(txtCodigoOpcion);
		
		// txtNombreOpcion
		txtNombreOpcion = new TextField();
		txtNombreOpcion.setStyleName("fieldRequired");
		txtNombreOpcion.setImmediate(false);
		txtNombreOpcion.setWidth("300px");
		txtNombreOpcion.setHeight("-1px");
		txtNombreOpcion.setInputPrompt("Nombre");
		txtNombreOpcion.setSecret(false);
		pnlOpcionFila1.addComponent(txtNombreOpcion);
		
		return pnlOpcionFila1;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlOpcionFila2() {
		// common part: create layout
		pnlOpcionFila2 = new HorizontalLayout();
		pnlOpcionFila2.setImmediate(false);
		pnlOpcionFila2.setWidth("-1px");
		pnlOpcionFila2.setHeight("-1px");
		pnlOpcionFila2.setMargin(false);
		pnlOpcionFila2.setSpacing(true);
		
		// cmbTipoOpcion
		cmbTipoOpcion = new ComboBox();
		cmbTipoOpcion.setImmediate(false);
		cmbTipoOpcion.setWidth("210px");
		cmbTipoOpcion.setHeight("-1px");
		pnlOpcionFila2.addComponent(cmbTipoOpcion);
		
		// txtOrdenOpcion
		txtOrdenOpcion = new TextField();
		txtOrdenOpcion.setImmediate(false);
		txtOrdenOpcion.setWidth("80px");
		txtOrdenOpcion.setHeight("-1px");
		txtOrdenOpcion.setInputPrompt("Orden");
		txtOrdenOpcion.setSecret(false);
		pnlOpcionFila2.addComponent(txtOrdenOpcion);
		
		// cmbPadreOpcion
		cmbPadreOpcion = new ComboBox();
		cmbPadreOpcion.setImmediate(false);
		cmbPadreOpcion.setWidth("300px");
		cmbPadreOpcion.setHeight("-1px");
		pnlOpcionFila2.addComponent(cmbPadreOpcion);
		
		return pnlOpcionFila2;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlOpcionFila3() {
		// common part: create layout
		pnlOpcionFila3 = new HorizontalLayout();
		pnlOpcionFila3.setImmediate(false);
		pnlOpcionFila3.setWidth("-1px");
		pnlOpcionFila3.setHeight("73px");
		pnlOpcionFila3.setMargin(false);
		pnlOpcionFila3.setSpacing(true);
		
		// txtADescripcionOpcion
		txtADescripcionOpcion = new TextArea();
		txtADescripcionOpcion.setImmediate(false);
		txtADescripcionOpcion.setWidth("300px");
		txtADescripcionOpcion.setHeight("73px");
		txtADescripcionOpcion.setInputPrompt("Descripción");
		pnlOpcionFila3.addComponent(txtADescripcionOpcion);
		
		// cmbEstatus
		cmbEstatus = new ComboBox();
		cmbEstatus.setImmediate(false);
		cmbEstatus.setWidth("-1px");
		cmbEstatus.setHeight("-1px");
		pnlOpcionFila3.addComponent(cmbEstatus);
		
		return pnlOpcionFila3;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlOpcionFila4() {
		// common part: create layout
		pnlOpcionFila4 = new HorizontalLayout();
		pnlOpcionFila4.setImmediate(false);
		pnlOpcionFila4.setWidth("-1px");
		pnlOpcionFila4.setHeight("-1px");
		pnlOpcionFila4.setMargin(false);
		pnlOpcionFila4.setSpacing(true);
		
		// btnGrabarOpcion
		btnGrabarOpcion = new Button();
		btnGrabarOpcion.setCaption("Actualizar");
		btnGrabarOpcion.setImmediate(true);
		btnGrabarOpcion.setWidth("-1px");
		btnGrabarOpcion.setHeight("-1px");
		pnlOpcionFila4.addComponent(btnGrabarOpcion);
		
		// btnEliminarOpcion
		btnEliminarOpcion = new Button();
		btnEliminarOpcion.setCaption("Eliminar");
		btnEliminarOpcion.setImmediate(true);
		btnEliminarOpcion.setWidth("-1px");
		btnEliminarOpcion.setHeight("-1px");
		pnlOpcionFila4.addComponent(btnEliminarOpcion);
		
		return pnlOpcionFila4;
	}



}
